### ISSUE TITLE
Demo Crashes Instantly on Galaxy S5

### ISSUE THREAD

**Issue by image28** [googlesamples/cardboard-unity#1]
Adb log bellow...

W/ActivityManager(  864): mDVFSHelper.acquire()

E/dalvikvm( 9084): >>>>> Normal User

E/dalvikvm( 9084): >>>>> com.nvisions.cardboardvr [ userId:0 | appId:10237 ]

D/dalvikvm( 9084): Late-enabling CheckJNI

I/ActivityManager(  864): Config changes=480 {0 1.0 530mcc24mnc en_NZ ldltr sw360dp w640dp h335dp 480dpi nrml long land finger -keyb/v/h -nav/h s.23}

D/dalvikvm( 9084): Trying to load lib /mnt/asec/com.nvisions.cardboardvr-2/lib/libRenderingPlugin.so 0x42d24388

D/dalvikvm( 9084): Added shared lib /mnt/asec/com.nvisions.cardboardvr-2/lib/libRenderingPlugin.so 0x42d24388

D/dalvikvm( 9084): Trying to load lib /mnt/asec/com.nvisions.cardboardvr-2/lib/libmain.so 0x42d24388

D/dalvikvm( 9084): Added shared lib /mnt/asec/com.nvisions.cardboardvr-2/lib/libmain.so 0x42d24388

I/Unity   ( 9084): gles_mode = 0 (integer)

I/Unity   ( 9084): splash_mode = 0 (integer)

I/Unity   ( 9084): hide_status_bar = True (bool)

I/Unity   ( 9084): useObb = False (bool)

I/Unity   ( 9084): development_player = True (bool)

D/Unity   ( 9084): surfaces: attach glview

W/dalvikvm( 9084): Unable to resolve superclass of Lcom/google/vrtoolkit/cardboard/proto/Phone$PhoneParams; (1646)

W/dalvikvm( 9084): Link of class 'Lcom/google/vrtoolkit/cardboard/proto/Phone$PhoneParams;' failed

E/dalvikvm( 9084): Could not find class 'com.google.vrtoolkit.cardboard.proto.Phone$PhoneParams', referenced from method com.google.vrtoolkit.cardboard.ScreenParams.createFromInputStream

W/dalvikvm( 9084): VFY: unable to resolve new-instance 1710 (Lcom/google/vrtoolkit/cardboard/proto/Phone$PhoneParams;) in Lcom/google/vrtoolkit/cardboard/ScreenParams;

D/dalvikvm( 9084): VFY: replacing opcode 0x22 at 0x004e

W/dalvikvm( 9084): VFY: unable to resolve exception class 1645 (Lcom/google/protobuf/nano/InvalidProtocolBufferNanoException;)

W/dalvikvm( 9084): VFY: unable to find exception handler at addr 0x5e

W/dalvikvm( 9084): VFY:  rejected Lcom/google/vrtoolkit/cardboard/ScreenParams;.createFromInputStream (Landroid/view/Display;Ljava/io/InputStream;)Lcom/google/vrtoolkit/cardboard/ScreenParams;

W/dalvikvm( 9084): VFY:  rejecting opcode 0x0d at 0x005e

W/dalvikvm( 9084): VFY:  rejected Lcom/google/vrtoolkit/cardboard/ScreenParams;.createFromInputStream (Landroid/view/Display;Ljava/io/InputStream;)Lcom/google/vrtoolkit/cardboard/ScreenParams;

W/dalvikvm( 9084): Verifier rejected class Lcom/google/vrtoolkit/cardboard/ScreenParams;

W/dalvikvm( 9084): threadid=1: thread exiting with uncaught exception (group=0x4201ada0)

W/ActivityManager(  864):   Force finishing activity com.nvisions.cardboardvr/com.google.vrtoolkit.cardboard.plugins.unity.UnityCardboardActivity

I/ActivityManager(  864): Config changes=480 {0 1.0 530mcc24mnc en_NZ ldltr sw360dp w360dp h615dp 480dpi nrml long port finger -keyb/v/h -nav/h s.24}

W/ActivityManager(  864): mDVFSHelper.release()

D/dalvikvm( 8621): GC_CONCURRENT freed 2060K, 45% free 12036K/21520K, paused 2ms+1ms, total 12ms

D/dalvikvm( 8621): WAIT_FOR_CONCURRENT_GC blocked 6ms

I/ActivityManager(  864): Process com.nvisions.cardboardvr (pid 9084) (adj 9) has died.

**Comment by smdol** [comment]
Each time this bug has been reproduced locally it turned out that the libprotobuf jar file was accidentally left out of the build.
