### ISSUE TITLE
support for Unity x86 builds

### ISSUE THREAD

**Issue by ph0b** [googlesamples/cardboard-unity#10]
Hi,

When targeting Android, Unity now builds apps for both armv7 and x86 targets.
However the cardboard plugin embeds only the armv7 version of libRenderingPlugin.so, which breaks the ability to build for x86 targets.

Would it be possible to update the plugin in order to integrate the x86 version of this native library as well ?
i.e. moving Plugins/Android/libs/libRenderingPlugin.so to Plugins/Android/libs/armeabi-v7a/
And adding its x86 version into Plugins/Android/libs/x86/ ?

Thanks.

**Comment by smdol** [comment]
Should work in v0.4.5 now.

**Comment by alex-nac** [comment]
Still not working. Only arm version of lingvr.so included:
<img width="175" alt="screen shot 2017-11-08 at 12 58 08" src="https://user-images.githubusercontent.com/15358082/32542695-7a966656-c484-11e7-9b61-98d369bc767a.png">

**Comment by nathanmartz** [comment]
This is by design. We only support ARM based systems.

**Comment by alex-nac** [comment]
Oh, I've got it now. Thanks!

**Comment by rusmaxham** [comment]
There is experimental support for x86 devices in the [latest release](https://github.com/googlevr/gvr-unity-sdk/releases).
