### ISSUE TITLE
0.5.2 Broken stereo camera when enabling Cardboard on Android

### ISSUE THREAD

**Issue by Oshroth** [googlesamples/cardboard-unity#101]
I'm having an issue where the distortion cutout for Cardboard is reversed i.e. The outer parts of the screen that would normally be black are displaying the stereo cameras and the inner parts that would normally be displaying the distortion-corrected cameras are instead black.

It occurs while VR mode is enabled if VR mode was not enabled by default.

It doesn't happen in the editor.

I am using Unity 5.2.2f1 and an empty project with a selection of various Android tablets and phones which all exhibit the issue.

![screen](https://cloud.githubusercontent.com/assets/10400354/10681181/5de36b6c-7972-11e5-8d41-25c3352e17c6.png)

**Comment by smdol** [comment]
On your Main Camera, set the Clear Flags to solid color, and in the Background Color, set alpha to 255.  Does that help?  Let me know either way.

**Comment by Oshroth** [comment]
Setting the Clear Flags and Background colour on the MainCamera and the stereo cameras didn't have any effect. I have Distortion Correction set to Unity, if I have it set to Native the entire screen is black instead of the above reversed cutout

**Comment by smdol** [comment]
OK, I'll go back through my notes tonight -- that flags thing was the first thing that leapt to mind -- but I did manage to achieve this effect once and then fix it.  If you can, would you be willing to send me a DropBox link to this mini-project?

**Comment by Oshroth** [comment]
http://studiogrow.org/Cardboard%20Raw%20Test.zip

**Comment by doctormobius** [comment]
Whenever this happens to me, tap the Google Cardboard cog to pop up the "Set up your viewer" panel... going back to the game after this clears it without needing to restart the app completely.

**Comment by pjohnsonbue** [comment]
I have a similar problem. In my case, the cameras are rendered correctly, but the outer portions show the skybox. The gyroscope is not working. If I press the settings cog and go back, the gyroscope begins to work again.

**Comment by smdol** [comment]
Got sidetracked last week with other issues.  Will take a look ASAP.

**Comment by smdol** [comment]
OK, reproduced and figured out the problem.  You can work around it for now by calling UpdateStereoValues() on the main StereoController class right after you enabled VR Mode, like so:

    Cardboard.Controller.UpdateStereoValues()

The problem is that the stereo cameras' targetTexture is not updated to point to the newly created RenderTexture.  Definitely a bug.

**Comment by pjohnsonbue** [comment]
Thanks for looking into this. The suggested fix did not work for me. Note that gyro is not working in either VR or non-VR mode. I updated from the previous SDK by deleting the cardboard & Plugins/iPhone folders as suggested in the docs. Perhaps it's related to this? After reinstalling old SDK, still did not work. Had to roll back to an earlier project with previous SDK to regain cardboard functionality.

**Comment by smdol** [comment]
@pjohnsonbue I suspect you're problem is related but not quite the same as @Oshroth (at least the gyro part).  If you get a chance to try 0.5.2 again, can you see if there's anything in your adb logcat?
