### ISSUE TITLE
Unity 5.2.1f1 & 0.5.2: CardboardAdapter prefab only updates rotation for right eye

### ISSUE THREAD

**Issue by arraypad** [googlesamples/cardboard-unity#103]
When using an existing camera and adding a CardboardAdapter prefab as its child, the right eye viewport updates correctly but the left eye only updates when the camera's position is changed.

I.e. the left eye viewport doesn't respond to the orientation of the device.

This only happens when building on a device (testing with Nexus 5 on Android 6 - target API level is 19/4.4), everything looks fine when playing within the editor.

**Comment by arraypad** [comment]
Same with 5.2.2f1 & 0.5.2

**Comment by smdol** [comment]
This should be fixed in v0.6 of the SDK.  (Make sure you add a StereoController to the existing camera in addition to the CardboardAdapter as a child.)
