### ISSUE TITLE
Unity 5.2.1f1 & 0.5.2: CardboardMain prefab changing NeckModelScale has no effect

### ISSUE THREAD

**Issue by arraypad** [googlesamples/cardboard-unity#104]
When using the CardboardMain prefab, changes to the NeckModelScale value seem to have no effect.  I'm trying to set it to 0f but have also tried small values above 0 - the main camera position is still changed as if NeckModelScale = 1.

This is case whether changing it in the inspector or in script using Cardboard.SDK.NeckModelScale.

This is observable both playing in the editor and on a Nexus 5.

**Comment by arraypad** [comment]
Same with Unity 5.2.2f1 & 0.5.2

**Comment by smdol** [comment]
Just checked this with the current build.  I'm not seeing this behavior.  When the neck model scale is 0, the CardboardHead's position stays at 0,0,0 for me.
