### ISSUE TITLE
Unity 5.2.1f1/5.2.2f1 & 0.5.2: Stretched view when starting in landscape orientation

### ISSUE THREAD

**Issue by arraypad** [googlesamples/cardboard-unity#106]
When in landscape orientation the eye viewports are stretched.

![stretched](https://cloud.githubusercontent.com/assets/451166/10716130/7dc42268-7b26-11e5-81f6-3ad524aa848e.png)

This is observable in any of the following cases:
* Default orientation is set to Landscape Left
* Default orientation is set to Auto Rotation but only Landscape Left is selected
* Default orientation is set to Auto Rotation, all orientations are selected, but calling `Screen.orientation = ScreenOrientation.LandscapeLeft;` in script.

This only happens when building on a device (testing with Nexus 5 on Android 6 - target API level is 19/4.4), everything looks fine when playing within the editor.

The only configuration I've found which doesn't have this issue requires *all* of the following:
* Default orientation is set to Auto Rotation
* Both Landscape Left and Portrait orientations are selected
* Not setting `Screen.orientation` in script
* **Start app with device in portrait orientation, then rotate to landscape**

As suggested in CardboardAndroidDevice.cs I've tried commenting out the GetDisplayMetrics method - no change.

I've tried the following log line just before the return in CardboardAndroidDevice.cs:GetDisplayMetrics:
```Debug.Log("METRICS: " + width + ", " + height + " @ " + metrics[3] + " - " + metrics[2] + " - " + Screen.dpi);```
This prints the same whether the app is started with the device in portrait or landscape orientation:
```METRICS: 1920, 1080 @ 443.345 - 442.451 - 442.898```

The DisplayMetricsAndroid workaround listed in #88 doesn't seem to have any effect.

**Comment by nathanmartz** [comment]
Cannot repro.
