### ISSUE TITLE
Escape key in Unity editor triggers SDK.BackButtonPressed and SDK.Tilted in wrong and inconsistent Time.frameCount

### ISSUE THREAD

**Issue by fredsa** [googlesamples/cardboard-unity#109]
When creating a project which targets both Cardboard and Standalone (desktop), it may be desirable to:
- use SDK.BackButtonPressed or SDK.Tilted while running with Cardboard
- use Input.GetKeyDown/Up(KeyCode.ESC) when not running in Cardboard

However, in 0.5.2 of the SDK, when running in the Unity editor, there are a few problems:
1. SDK.BackButtonPressed and SDK.Tilted are both triggered by hitting ESC, which isn't a useful mapping
2. SDK.BackButtonPressed and SDK.Tilted are each unexpectedly triggered in different frames, which is unhelpful
3. SDK.BackButtonPressed and SDK.Tilted are each triggered in a different frame than the corresponding Input.GetKeyDown/Up(KeyCode.ESC), which is annoying

To reproduce:
Create a C# script with an Update() method which listens for the Cardboard and Input.KeyDown/Up events, then find that:

If
- Input.GetKeyDown(KeyCode.ESC) is triggered in frame N
and:
- Input.GetKeyUp(KeyCode.ESC)  is triggered in frame N + M

then:
- Cardboard.SDK.BackButtonPressed is triggered in frame N +1 (instead of frame N)
- Cardboard.SDK.Tilted is triggered in frame N + M +1 (instead of frame N+M)
- Cardboard.SDK.BackButtonPressed and Cardboard.SDK.Tilted are triggered in different frames (i.e. N+1 and N+M+1), because one is triggered after KeyDown and the other after KeyUp

**Comment by fredsa** [comment]
To clarify, the fact Cardboard.SDK.BackButtonPressed and Cardboard.SDK.Tilted trigger in different frames than the originating 'ESC' key up/down means that code in, say, an 'Update()' call which tries to handle either ESC key up/down or Cardboard.SDK.BackButtonPressed and Cardboard.SDK.Tilted will end up firing twice as the two different triggers return in subsequent frames, which means in different calls to 'Update()'.

**Comment by smdol** [comment]
That's a bug:  The Esc key used to be matched up with Cardboard.SDK.Tilted, but is now supposed to be matched up with Cardboard.SDK.BackButtonPressed.  Looks like the old mapping didn't get deleted.

**Comment by fredsa** [comment]
Thanks. Note also that the frame (Time.frameCount) when
Cardboard.SDK.BackButtonPressed
triggers should be the same as when Input.GetKeyUp(KeyCode.ESC) triggers,
and not one frame later.
​

**Comment by nathanmartz** [comment]
Bug filed internally.
