### ISSUE TITLE
Warning when building sample: Unable to find unity activity in manifest

### ISSUE THREAD

**Issue by claywilkinson** [googlesamples/cardboard-unity#11]
Unable to find unity activity in manifest. You need to make sure orientation attribute is set to fullSensor manually.
UnityEditor.PostprocessBuildPlayer:Postprocess(BuildTarget, String, String, String, Int32, Int32, String, String, BuildOptions, RuntimeClassRegistry)

**Comment by smdol** [comment]
There is a possible answer here. 
    http://stackoverflow.com/a/27587358/4372377

**Comment by KingWu** [comment]
Face the same issue

**Comment by smdol** [comment]
Fixed in v0.4.5.
