### ISSUE TITLE
Stereo View Problem on iOS 9.1, Unity 5.2.2, Xcode 7.1, Cardboard SDK v0.5.2

### ISSUE THREAD

**Issue by MayisGM** [googlesamples/cardboard-unity#110]
Hi,

I am using Unity 5.2.2f1, Xcode 7.1, Cardboard Unity SDK v0.5.2 and iOS 9.1 device. You can see the problem in attached screenshot from device screen. The right eye is working normally, but the left eye looks like rendering only one frame at start and is freezing. Right eye is getting gyro input and working with normal FPS. I figured out that the problem is disappearing when I am disabling directional light shadows: in this case both two eyes are working very good. It is very important for my project to use soft shadows and tomorrow is deadline of my project. Please help me... In Android devices everything is working normally. The problem is only related on iOS.

![img_0558](https://cloud.githubusercontent.com/assets/15582338/10871495/c802ff9c-80f9-11e5-9f58-d5ba1460d7e0.PNG)

**Comment by nathanmartz** [comment]
Fixed in 0.6.0.
