### ISSUE TITLE
iOS URL Parsing and Syncing

### ISSUE THREAD

**Issue by Matty3D** [googlesamples/cardboard-unity#111]
I have been developing my VR app in Unity for awhile on my old iPhone 5 and now my new iPhone 6S Plus.

The problem is that the QR scanner for reading my Headset that is included in the SDK has been always broken for me returning "Problem Parsing the URL" every time I scan a QR code.
I'm using the Powis ViewR, and you can test their QR code on their webpage
http://powiscustom.com/collections/powis-virtual-reality-kits/products/powis-virtual-reality-kit

I was initially able to get around this problem by Enabling Syncing to the Google Cardboard app, As the QR code scanner in the app works. but now the syncing to the app appears to be broken too. (I can select the google cardboard app to sync, but my viewer remains as "Default Viewer" despite the fact its set to Powis ViewR)

Perhaps it's something wrong I'm doing that I can fix? or it's a problem with the plugin itself.

**Comment by Matty3D** [comment]
Ok I've solved one of the issues, The answer to fix the QR scanner is actually in the latest release notes:
https://developers.google.com/cardboard/unity/release-notes

As for the Syncing Cardboard app issues, It's actually something wrong with XCode or my App setup in XCode. There's some kind of error happening preventing the iCloud documents from working, When I turn on the iCloud entitlement there's  a red ! next to "Add the iCloud entitlement to your App ID". Attempts to fix the issue or change iCloud settings causes Xcode to crash.

Will post updates if I solve the issue, but for now I can at least get my app configured for my viewer.

**Comment by brianchasalow** [comment]
@smdol  there is a bug where if you don't have the Cardboard app installed yet, and try to Sync with Cardboard, the iOS app will crash. Please mark that one on your radar. If you have the iCloud entitlements setup  and have already installed the Cardboard app from the app store, everything will work fine.

**Comment by smdol** [comment]
Ah, OK.  It's supposed to tell you to install Cardboard (and not crash).  This must be a regression because I'm pretty sure it worked in the prior SDK.

**Comment by smdol** [comment]
Well, v0.6 of the SDK, and for better or worse we are deprecating the Sync with Cardboard option.  It has not proven robust and workable, for this reason and others.  For the time being, each app will have an independent viewer setting on iOS.

**Comment by brianchasalow** [comment]
that's a bummer :-(

**Comment by Cross22** [comment]
Very disappointing.
