### ISSUE TITLE
Normal mapping with 0.5.2

### ISSUE THREAD

**Issue by justinwasilenko** [googlesamples/cardboard-unity#115]
I had normal mapping working with 0.5.1 and now with 0.5.2 it's gone when I build the game. Works fine in the editor when I preview the game but not running on the phone. Samsung S3, and built using Unity 5.2.
Does the new Unit distortion correction change the normal mapping or could it be something else?

**Comment by smdol** [comment]
It could be the Unity distortion correction.  If you set Distortion Correction to "Native" on the Cardboard component, it will go back to using the old method.  Let me know if that makes a difference.

**Comment by MiCkSoftware** [comment]
Is it real-time or baked (directional light maps)? In my case I had issues
with LM and unity distortion correction fixed it.

**Comment by justinwasilenko** [comment]
It was both real-time and baked, I found the issue which was the compression settings on the texture. I had set them to ASTC which did not work for normal mapping. Setting the normal textures to the default compressed fixed my issue. Probably more my fault then anything. My game is looking great now.

Not really an issue so closing this.
