### ISSUE TITLE
Cannot hold tap when using cardboard view

### ISSUE THREAD

**Issue by andiwinata** [googlesamples/cardboard-unity#118]
Hello,

I just found out this issue, so basically when I try to detect tap hold it is not working.
Everytime after I tap down, it just automatically detects tap off immediately.

I've tried using

Input.GetMouseButtonDown(0) 
Input.GetMouseButtonUp(0)
Input.GetMouseButton(0)

Input.Touch()

and they are giving the same results, just immediately detects 'Up' shortly after 'Down'

**Comment by smdol** [comment]
Turn off TapIsTrigger in the Cardboard component properties.

**Comment by andiwinata** [comment]
Ah I see,
thanks it is fixed now
