### ISSUE TITLE
Cardboard SDK Support in other engines

### ISSUE THREAD

**Issue by zulman** [googlesamples/cardboard-unity#119]
Hi,

Zillions times sorry for creating it here (it's the only place where actual Cardboard developers are responding). Is it possible to get any information about implementing Cardboard SDK support in Unreal Engine 4? Epic Games team is ignoring this question, may be this implementation will come from Google? 

Thank you and sorry one more time.

**Comment by smdol** [comment]
Definitely appreciate your feedback.  We prioritize SDK development based on developer demand, so it's very useful to hear that developers are eager for Cardboard support in Unreal.

**Comment by zulman** [comment]
Thank you :) It's great to hear it. As i know as UE4 community participant Cardboard support in this engine is extremely popular question. Also i know at least 2 teams in Russia who have to switch back to Unity just because there is now official support of Cardboard SDK. If it's required i will able to give more details olegchumakovzulman [AT] gmail [DOT] com
