### ISSUE TITLE
Position Tracking Unity

### ISSUE THREAD

**Issue by supachailllpay** [googlesamples/cardboard-unity#124]
I want to be able to track head position. For example, when I move head forward the camera should move forward too and so on.
I see trackPosition attribute in CardboardHead but it seems doesn't work properly. I try to print out Cardboard.SDK.HeadPose.Position but it always return (0.0, 0.0, 0.0) or just (0.0, 0.0, 0.1). Am I missing something?

**Comment by smdol** [comment]
TrackPosition is there because at some point in the future the Cardboard SDK will be used on a device like Tango that supports full position and orientation tracking.  On current phones, there is no positional tracking sensor, so the setting has no operational effect.

**Comment by supachailllpay** [comment]
Ah ok, got it. Thanks!
