### ISSUE TITLE
OnePlus One right eye field of view

### ISSUE THREAD

**Issue by justinwasilenko** [googlesamples/cardboard-unity#127]
I have a customer with a OnePlus One reporting seeing double, or a blurry image in my game End Space VR.

Here is a screenshot he sent me (OnePlus One):
![screenshot_2015-12-15-12-35-57](https://cloud.githubusercontent.com/assets/11709400/11837284/2ed68b86-a3e0-11e5-97e9-f6cfe6d7ff45.png)

And here is a screenshot I made using my Samsung S3,
![samsung s3 end space vr v1 01](https://cloud.githubusercontent.com/assets/11709400/11837295/468d429c-a3e0-11e5-8f01-dc723d385fde.png)

You can see the right eye has a much different field of view. I asked the customer to reset his data and cache of the cardboard app, but the problem persists.

**Comment by smdol** [comment]
For OnePlus One, the first thing we tell people is to change to phone's DPI from the factory default (and incorrect) value of 480 to the correct value if 401.  That practically always solves this issue.

**Comment by justinwasilenko** [comment]
Yep that solved the issue, thanks!
