### ISSUE TITLE
Button to disable VR mode throughout scenes

### ISSUE THREAD

**Issue by alib0ng0** [googlesamples/cardboard-unity#129]
Hi there - is it possible to have a menu, where VR mode is disabled throughout all scenes?

I know this is possible for the current scene

Any help would be appreciated

**Comment by smdol** [comment]
There is a Cardboard Codelab that shows how one could implement this:

https://io2015codelabs.appspot.com/codelabs/cardboard-unity#5

**Comment by alib0ng0** [comment]
Your sire are a legend! many thanks
