### ISSUE TITLE
Linker error: Cardboard SDK 0.5.2, Unity 5.2.1, Xcode 7.1.1, -ObjC flag

### ISSUE THREAD

**Issue by chrissweeney1p** [googlesamples/cardboard-unity#130]
There appears to be an issue building an iOS project when the "-ObjC" compiler flag is used (in this case, because the Cast Remote Display Plugin requires this flag). The output is below; is this an issue that can be addressed? Thank you.

Undefined symbols for architecture arm64:
  "gvr::CreateMainApp__EXPECTED_EXACTLY_ONE_VR_MAIN_APP_STATEMENT__(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)", referenced from:
      l001 in libvrunity.a(vr_ios.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by smdol** [comment]
It is definitely being addressed for an upcoming release.  As a workaround, try including this code in a C++ file:

    #include <vector>
    namespace gvr {
        class VrApp;
        VrApp* CreateMainApp__EXPECTED_EXACTLY_ONE_VR_MAIN_APP_STATEMENT__(const std::vector<std::string>&) { return nullptr; }
    }

**Comment by chrissweeney1p** [comment]
Excellent, this allowed the build to succeed; thanks!

**Comment by smdol** [comment]
This should also be fixed in the new v0.6 release -- we pretty much did exactly the same thing in the native code.
