### ISSUE TITLE
Pre-loaded viewer profile on app install

### ISSUE THREAD

**Issue by bmasala** [googlesamples/cardboard-unity#131]
Is it possible to load an app with a cardboard viewer profile assuming it's the first one installed on the users phone? 

Scenario 1. User downloads app and since it's the first cardboard app on the phone, the viewer profile is set to our headset's.
Scenario 2. User downloads app but has other cardboard apps installed. Viewer profile doesn't change.

**Comment by smdol** [comment]
You can edit Cardboard.cs and set the DefaultDeviceProfile variable.  (Sorry, no editor UI for this.)  This acts exactly the way you spelled out.

**Comment by bmasala** [comment]
Wonderful - Thanks!
