### ISSUE TITLE
Disable Cardboard Onboarding dialog.

### ISSUE THREAD

**Issue by andr3wmac** [googlesamples/cardboard-unity#134]
It would be nice to have an SDK wide setting to disable the cardboard onboarding dialog. We've had to modify CardboardiOSDevice.cs to disable the screen.

**Comment by interactivespace** [comment]
I think when you set the DefaultDeviceProfile URI the app doesn't open the onboarding dialog.

File Cardboard.cs  public Uri DefaultDeviceProfile = "your profile url";

https://www.google.com/get/cardboard/viewerprofilegenerator/

**Comment by andr3wmac** [comment]
That does appear to be true but in my opinion it should still be able to be disabled via a simple bool or function call. I can close this issue if Google has no intention of implementing this.

**Comment by smdol** [comment]
For now, we've had to disable the auto-launching of the onboarding altogether.  The functions to launch it and set it as "done" still exist in CardboardiOSDevice.cs, if you want to use it.
