### ISSUE TITLE
Samsun Note4 issue: Scene Incline

### ISSUE THREAD

**Issue by tim-hub** [googlesamples/cardboard-unity#135]
With gear vr1, this is a good fit and good vr experience.

But when develop the cardboard vr app, there is a very weired problem, the scene incline and swing very slowly. I do not know why, due to the same app in another phone (oppo find5), it is fine.

Even in aframe.io/webvr, in browser, the vr scene is normal and do not incline.

Could some know this issue too? Waiting your help.

**Comment by nathanmartz** [comment]
This is an issue with our drift correction algorithm and the Note 4. We're constantly working on improving drift correction. Note that GearVR actually includes its own IMU to avoid phone specific issues like this.
