### ISSUE TITLE
Blend of textures instead of render texture view of the camera

### ISSUE THREAD

**Issue by ValentinChareyre** [googlesamples/cardboard-unity#138]
Hello everybody,

I am currently running into the following problem with the Cardboard SDK 0.5.2 and Unity 5.3.1 :

**Sometimes**, when I disable and enable the VR Mode (stereoscopic view), the *Render Texture* used to render the view of the stereoscopic cameras is replaced by a blend of all the textures of my scene and I don't have the "mask effect" around the render.

You will find a screenshot below to illustrate what I am saying :

![screenshot_2016-01-13-12-34-48](https://cloud.githubusercontent.com/assets/6215725/12294899/f7a76796-b9fd-11e5-907e-dcbcf6a191a3.png)

I can't manage to reproduce this bug each time.

The only way to have the stereoscopic view back to normal is to uninstall the application and install it back again. If I disable the stereoscopic view and enable it, the result is the same. (Same result if I close the application, empty the RAM and restart the application).

I only have tested my application with a Samsung Galaxy S4 (GT-I95000) with Android 4.4.2

Maybe, I should update the SDK to the new 0.6 version ?

Thanks in advance.

-----

EDIT : I managed to reproduce the bug with a "simple" project :

- Create new scene
- Add the Cardboard Main prefab + Event System with the Gaze Input Module
- Add a cube and add it the following script called "Test.cs":
```C#
using UnityEngine;
using UnityEngine.SceneManagement;

public class Test : MonoBehaviour
{
	public void SwitchVRMode()
	{
		Cardboard.SDK.VRModeEnabled = !Cardboard.SDK.VRModeEnabled ;
	}
	
	public void GoToScene()
	{
		SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex) ;
	}
}
```
- In the `Awake` function of the Google Cardboard Script, add this at the **end** of the function :
```C#
    if(PlayerPrefs.HasKey("VRModeEnabled"))
        VRModeEnabled = PlayerPrefs.GetInt("VRModeEnabled") > 0;
```
- In the `OnDestroy` function of the Google Cardboard Script, add this at the **beginning** of the function :
````C#
PlayerPrefs.SetInt("VRModeEnabled", VRModeEnabled ? 1 : 0);
```
- Add a canvas (in world space) with two buttons
    - One button must call the SwitchVRMode function of the Test script
    - The other button must call the GoToScene function of the Test script
- Build the app, install it on your phone and run it
- Switch off the VR using the first button
- Reload the scene using the other button
- Switch on the VR using the first button


I use the PlayerPrefs to keep the VR mode value through my scenes

-----

As suggested here : http://stackoverflow.com/questions/30191001/google-cardboard-scene-not-rendering-properly-with-unity-5-when-depoly-to-androi I tried the following solutions

1. In Unity Editor, Under Game Object Hierarchy, go to CardboardMain>Head>MainCamera, turn off Direct Render property under Stereo Controller script.
2. Turn on Development Build under Build Settings.

If you combine the two solutions above, it fixes the problem in the example project I gave above but not in my real project... :angry:

**Comment by smdol** [comment]
Definitely try the new 0.6 release.  It should have a fix for this.

**Comment by Enumio** [comment]
I encountered the same problem, consloe says "releasing render texture2d" two times, that means for both eyes/cameras. The problem doesnt exist in Unity 5.1.3f1, everthing is fine there but in 5.3.1 this issue appears. I've tracked it down, it has something to do with antialiasing. If in quality settings you set antialiasing to 2x problem is gone, if AA is 0 issue appears.

I've tested it on nexus7 2013 and Galaxy s6.

I have managed to invoke the issue by swithing apps in taks manager. When i switch back to my app via android task manager this error occures.

Hope this helps a little, these are just mine experiences.

cheers :)

**Comment by smdol** [comment]
Hi @Enumio, which version of the Cardboard SDK are you using?

**Comment by Enumio** [comment]
0.5.2, i'm gonna try with 0.6.
I've just downloaded it.

**Comment by smdol** [comment]
OK.  Note: If you get a crash on resuming the app from the task mgr, we're working on that now.  You can fix by disabling CardboardAudioListener on the Main Camera.

**Comment by Enumio** [comment]
Im sorry i forgot to say that when i resume the app from task manager this issue happens but then when i go to task manager again and return to my app for the second time all goes away, rendering works normal. 

I'm sorry i forgot to mention this.

**Comment by Enumio** [comment]
Ok, i can report that this weird issue is gone, but the app carshes when exiting to task manager and the CardboardAudioListener is enabled.

I disabled it like you said and everything works fine.

**Comment by smdol** [comment]
OK, we've updated the SDK to disable the spatial audio in the prefabs for now, until the bug in Unity is fixed which causes the crash.

**Comment by ValentinChareyre** [comment]
I don't have the problem anymore using the SDK 0.6 ! :smile: Thank you @smdol and all the team who has worked on this great project  :clap: 

Thank you @Enumio for your time too ! With the SDL 0.6, I haven't changed the Anti aliasing value, and it still works ! :+1:
