### ISSUE TITLE
Cardboard UI appears briefly when loading new scene

### ISSUE THREAD

**Issue by nsroy** [googlesamples/cardboard-unity#139]
On Android, even if "VR Mode Enabled" is off, the Cardboard UI (settings, back button and alignment marker) appears briefly before disappearing.

**Comment by andr3wmac** [comment]
Apparently this is a known bug in the native code. I had the same issue here:
https://github.com/googlesamples/cardboard-unity/issues/136

**Comment by nsroy** [comment]
The new Cardboard SDK (0.6) released yesterday fixes this!

**Comment by smdol** [comment]
OK, I'll close the issue.
