### ISSUE TITLE
CardboardGUI refresh when loading a new scene

### ISSUE THREAD

**Issue by qwarnant** [googlesamples/cardboard-unity#14]
Hello,

I don't know if it is really a bug but in doubt, I post it. I have two scenes in my project, both are using the CardboardMain game object with a CardboardGUI attached to this object. 

In my CardboardGUI script on each scene, I've registered the OnGUI callback to the CardboardGUI class. When the player is loading the second scene, the GUI rendered on the first scene is not cleaned. If I want to remove the first scene GUI, I have to manually remove the OnGUI callback from the CardboardGUI class before the Application.LoadLevel call. Is it normal ?

**Comment by smdol** [comment]
Yes, that is what you are supposed to do.  See the [Cardboard Plugin Reference](https://developers.google.com/cardboard/unity/reference):

##### Code Changes to Scripts using `OnGUI()`

    void Start() {
        CardboardGUI.onGUICallback += this.OnGUI;
        // ...
    }

    void OnDestroy() {
        CardboardGUI.onGUICallback -= this.OnGUI;
        // ...
    }

    void OnGUI() {
        if (!CardboardGUI.OKToDraw(this)) return;
        // ...
    }

The reason it can't be automatic is that CardboardGUI does not know if your object will be used across level loads.  See:
    http://docs.unity3d.com/ScriptReference/Object.DontDestroyOnLoad.html

**Comment by qwarnant** [comment]
Okay, I understand ! Sorry, I had not seen these lines in the configuration yet.

Thank you for your answer.
