### ISSUE TITLE
Cardboard SDK v0.6 - iOS Crash on Startup

### ISSUE THREAD

**Issue by dill0wn** [googlesamples/cardboard-unity#140]
Today, I updated the project I'm working on to use 0.6 and ran into some issues.  To make things easier to troubleshoot, I made an empty project and imported `CardboardSDKForUnity.unitypackage` and `CardboardDemoForUnity.unitypackage ` from the current release (https://github.com/googlesamples/cardboard-unity/commit/65cb71f537a15ddc038245f0621c9a56007b7ece).  Unfortunately, I'm still seeing the same issue.  There's a crash on startup on my iPhone 6 Plus running iOS 9.2.  For my development environment I'm using Unity 5.3.1p1 with Mac OS 10.11.2

The error I'm seeing:

`Thread 21: signal SIGABRT`

And it comes from the following method in: `Il2CppInvokerTable.mm`

```objc
void* RuntimeInvoker_Void_t_224166001_0_Object_t_Int32_t1628762099_0 (const MethodInfo* method, void* obj, void** args)
{
	typedef void (*Func)(void* obj, Object_t * p1, int32_t p2, const MethodInfo* method); 
	// The above is the offending line
	((Func)method->method)(obj, (Object_t *)args[0], *((int32_t*)args[1]), method);
	return NULL;
}
```

The Callstack looks like: 

```
Thread 21
#0	0x00000001815c8140 in __pthread_kill ()
#1	0x0000000181690ef8 in pthread_kill ()
#2	0x0000000181539dac in abort ()
#3	0x00000001815f4384 in free ()
#4	0x00000001003aeb40 in RuntimeInvoker_Void_t_224166001_0_Object_t_Int32_t1628762099_0(MethodInfo const*, void*, void**) at /Users/dillon/Desktop/Unity5XCode/cardboard0.6/Classes/Native/Il2CppInvokerTable.cpp:962
#5	0x0000000100b7b600 in il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppObject**) at /Users/builduser/buildslave/unity/build/Tools/il2cpp/il2cpp/libil2cpp/vm/Runtime.cpp:345
#6	0x000000010055abc4 in ::Invoke() at /Users/builduser/buildslave/unity/build/Runtime/Scripting/Backend/ScriptingInvocation.cpp:180
#7	0x000000010060c198 in Invoke [inlined] at /Users/builduser/buildslave/unity/build/./Runtime/Scripting/Backend/ScriptingInvocation.h:50
#8	0x000000010060c188 in ::readCallback() at /Users/builduser/buildslave/unity/build/Runtime/Audio/AudioCustomFilter.cpp:181
#9	0x0000000100add9d4 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#10	0x0000000100add6f0 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#11	0x0000000100add6f0 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#12	0x0000000100add6f0 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#13	0x0000000100add6f0 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#14	0x0000000100add6f0 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#15	0x0000000100add6f0 in FMOD::DSPFilter::read(float**, int*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#16	0x0000000100aedc54 in FMOD::DSPSoundCard::read(void*, unsigned int*, FMOD_SPEAKERMODE, int, unsigned int) ()
#17	0x0000000100afbffc in FMOD::Output::mix(void*, unsigned int) ()
#18	0x0000000100afd398 in FMOD::OutputCoreAudio::updateMixer() ()
#19	0x0000000100b15dc0 in FMOD::Thread::callback(void*) ()
#20	0x000000018168fb28 in _pthread_body ()
#21	0x000000018168fa8c in _pthread_start ()
```

All of this is also shown in this screenshot:
<img width="1512" alt="screenshot 2016-01-13 15 51 36" src="https://cloud.githubusercontent.com/assets/1267330/12308131/6ff2e2ee-ba11-11e5-850e-eb95775ecb1f.png">

A Zip of My Project:
https://www.dropbox.com/s/h36l2u1fo64l2qb/Cardboard%20SDK%200.6%20-%20Sample.zip?dl=0

Notable Repro Steps (Some of which have been completed in the included .zipped project):
- Added the sample scene as the project's only scene in the build settings
- Switched build platform to iOS
- Made Security.framework a dependency of CardboardSDK.bundle in the plugin inspector.
- Built XCode project
- Set `Enable Bitcode` to `No` in XCode Build Settings
- Ran on device
- Runtime error!

I also decided to take a deeper look at the `cardboard-unity` repo, where I found: 
`cardboard-unity/blob/master/Samples/SpatialAudio/ProjectSettings/AudioManager.asset`  which has this line: `m_SpatializerPlugin: CardboardAudio Spatializer`

That wasn't set in my project.  I set it to use the CardboardAudio Spacializer and, unfortunately, the issue didn't go away.

Is anybody else seeing anything like this?

**Comment by smdol** [comment]
Potentially the same issue as #137, due to audio spatializer bug in Unity 5.2+.

**Comment by dill0wn** [comment]
@smdol: Following your suggestion in #137 and Removing the CardboardAudioListener, fixed it for me.  Thanks!
