### ISSUE TITLE
0.6SDK and discontinuation of Tilt (UX issue)

### ISSUE THREAD

**Issue by Delanir** [googlesamples/cardboard-unity#142]
I noticed one of the release notes mentioned that the Tilt event is no longer supported, and that we can make our Tilt functionality using the Input.acceleration.
Is there a standard way of implementing this Tilt mechanism?
The official cardboard app introduces this input mode in the demos. I think that in the name of uniformity it would be beneficial if all implementations that use Tilt, would have a Tilt that would function the same way and that feels the same.

**Comment by nathanmartz** [comment]
We are actually moving away from Tilt to exit functionality. It'll stay in the demos, but we don't recommend it as a standard. It's hard for users to do and often results in phones falling out of cardboard.
