### ISSUE TITLE
SDK 0.6.0 Crashes

### ISSUE THREAD

**Issue by Vectorizing** [googlesamples/cardboard-unity#143]
So the first thing I do to test a new SDK version is update it in my project and build it. From there I will install it on my Samsung S5 and do some tests. One of the tests I do is move the device rapidly up, down, left, right, side to side, etc. The reason I do this is because you never know what the user is going to do and it's good to test everything. Whenever I move my device rapidly the app crashes. So if the user wants to look around quickly they run the risk of crashing the app. This is a problem. 

I've run into issues similar to this. With SDK V0.5.2 if a user looked around quickly and then called, OnApplication.Quit() or Application.LoadLevel() (via button press) the app would crash. This turned out to be because of the OnTilt function. I could move the device as much as I wanted as fast as I wanted and it wouldn't crash until they tried to go home or exit the app. If I move the device slowly and then call these functions it works fine. (Previous Issues: https://github.com/googlesamples/cardboard-unity/issues/125 and https://github.com/googlesamples/cardboard-unity/issues/117)

To fix this I downgraded yet again to V5.1.0. For some reason this is the only version of the cardboard sdk that I have not had any issues with. A user can look around as quickly as they want, push buttons to go back to the main menu, and not crash at all. I have no idea why it works on this version but not the latest versions.

Back to V0.6.0... using Logcat it throws a SIGSEGV 11 error. The same error I would get on V0.5.2 (something memory related if I remember correctly).

The best way I can think of to recreate this issue is create an empty scene, drop the CardboardMain prefab in it. Throw in a cube and then build it. Install it on your device and then move your device quickly. (Just spin it, move it up and down, etc.) 

I'm at a loss here, I'm not sure what to do. In the past month I've had to downgrade all my apps from V0.5.2 to V0.5.1 because of bad ratings, crashes, etc. 

Anyone have any thoughts?

Thanks everyone.

**Comment by smdol** [comment]
With 0.6 is it crashing while moving the phone, or on LoadLevel/Quit?

**Comment by Vectorizing** [comment]
Just while the phone is moving. It's almost like the Cardboard SDK is having trouble calculating the values from the gyroscope so quickly and it ends up failing at some point. The LoadLevel and Quit work fine in V0.6.0, that was fixed. Now it just crashes while moving the phone rapidly. 

It's worth mentioning that in a completely normal scenario, no one should need to look around this quickly, but someone out there will move their phone rapidly one time and it will crash on them. I've had people file bug reports because of this. (Thus the downgrade to V0.5.1).

Thanks!

**Comment by smdol** [comment]
I tried reproducing this with my Nexus 5x, and couldn't get a crash to happen.  (I did almost fling it across the room though. -- maybe I have to move it differently?) You said it happens on your Samsung S5.  Do you know any other models it happens on from the bug reports?  I can ask the QA team to try -- they have many more models in their stock.

**Comment by Vectorizing** [comment]
Okay So I created a brand new project and wasn't able to reproduce the issue which means I get the honor of rebuilding an entire project. The quickest way I was able to get it to crash was to hold the phone and twist my wrist back and forth rapidly. But after creating this new project (instead of a new scene) I couldn't get it to crash. Looks like there is something in my project that is affecting this.

**Comment by smdol** [comment]
When you upgraded to 0.6, did you delete the old Cardboard and Plugins directories under Assets first?  I suggest trying that if possible.

**Comment by Vectorizing** [comment]
Yeah I've done all of that. I had to to that when I downgraded earlier in the month.

**Comment by smdol** [comment]
OK, I'm going to close the issue, but we can open it again if the problem crops up again.
