### ISSUE TITLE
SDK 0.6, Android - StereoController.stereoMultiplier not working

### ISSUE THREAD

**Issue by ITurchenko** [googlesamples/cardboard-unity#146]
Any changes cause no effect on cross-eye distance.
Here is example screenshots from Nexus 5, Android 6.0

stereoMultiplier = 0.5
![](https://i.gyazo.com/e349cd296fbdb53d1220e91f33ad5e9a.png)

stereoMultiplier = 3
![](https://i.gyazo.com/7a23049ec838be39a9e23e3a3f5b0634.png)

Should note, that this thing works fine on previous version of sdk (0.5.2).

**Comment by smdol** [comment]
Changing the stereo level will only take effect when UpdateStereoValues() is called.  This is for performance.  If you want to test it, turn on "Keep Stereo Updated" on the StereoController.

**Comment by ITurchenko** [comment]
Perhaps I'm not quite accurately described the problem. 
That's what I'm trying to say: in the 0.6 SDK I can't change the distance between the eyes.

Here is collage from different sdk&parameters.
![](https://i.gyazo.com/cdd794668939f91611601a86fb219027.png)

Anyway, thank you for trying to help me.

**Comment by smdol** [comment]
Interesting!  I did this in v0.6, and saw what you saw on the bottom (cubes moving inwards) -- in the editor.  I just had to enable Keep Stereo Updated on the StereoController.  Are you seeing the problem on the phone, in the editor, or both?

**Comment by ITurchenko** [comment]
I'm sorry I misled you with my last message. Turning on "Keep Stereo Updated" on the StereoController fixed my problem.

**Comment by smdol** [comment]
OK, good to hear.  The SDK is withing as intended here.  For performance, jyou can ust call UpdateSteteoValues from code when you know you need to, or equivalently, leave KeepStereoValues disabled when you are not changing values on the main camera.
