### ISSUE TITLE
Audio plugin | occlusion enhancement - gain fade

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#148]
Hi!

The new audio plugin is very good but I found that when an occlusion occurs the sound level is changing instantaneously which breaks realism a bit (in the real world there is a bias just like with light and shadows). 
I do not know what's the best CPU friendly solution but before 0.6 I was setting desired level as a target (which is absolutely wrong but makes a good illusion):

```C#
as.volume = Mathf.MoveTowards(as.volume, basevol * target, Time.deltaTime * FadeSpeed); 
```

Let me know what do you think!

**Comment by nathanmartz** [comment]
Hi. We already smooth the change that happens when occlusion occurs. Maybe it's happening too quickly for you and sounds instantaneous? You can change the rate by editing CardboardAudio.cs and modifying occlusionLerpSpeed to be a lower number.

**Comment by nathanmartz** [comment]
Closing as we're tracking this internally now.

**Comment by MiCkSoftware** [comment]
Thanks for the quick feedback.
Too bad it's a const but I'll accommodate :)
For the record I lowered the value to 3.0f and was still not satisifed. 
In the end I set it to 5f and halved per raycast hit occlusion increase
```C# 
//occlusion += 1.0f;
occlusion += .5f;
```
