### ISSUE TITLE
Audio plugin | occlusion enhancement - Masks

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#149]
Hi, 

Another proposal for enhancement: in my scene I wish I could control which geometry occludes audio and which one does not. I think this is enough and more CPU friendly than processing whole scene geometry.On top of the fact that I do not want small objects to occlude.

Prior to 0.6, I was achieving this behavior by masking ray casts from the source to the listener:

```C#
// Layers that occlude audio
public LayerMask Mask;
//...
// Count hits; the more hits the more the sound is fade out
RaycastHit[] hits = Physics.BoxCastAll (listener.position, Vector3.one/10f, transform.position, Quaternion.identity, 100f, Mask.value);
//....
```

Capitalizing on this, I think it would be quite easy to add a property defining the occlusion intensity.
And it would be so great if you could add a low pass / high pass filter per occlusion (CPU load?) for even more realism.

Let me know what are your thoughts!
Cheers!

**Comment by nathanmartz** [comment]
Thanks for the feedback. We'll look into these requests for a future version of the SDK. The LayerMask should be especially straightforward.

**Comment by nathanmartz** [comment]
Closing as we're tracking this internally now.

**Comment by MiCkSoftware** [comment]
Thanks for implementing in 0.7 !!! Cheers !
