### ISSUE TITLE
DemoScene is not working on Android mobile

### ISSUE THREAD

**Issue by spencergong** [googlesamples/cardboard-unity#15]
please look at picture as follow
![0101](https://cloud.githubusercontent.com/assets/10891602/6090537/abbb52e0-aeb7-11e4-985f-5172738fd87f.png)

**Comment by qwarnant** [comment]
Maybe you should give us more information about your problem in order to find an answer more easily ? ;-)
What is your : 
- Your Android version
- Your phone model 
- Your unity3d version

**Comment by spencergong** [comment]
Unity3D pro 4.5 & 4.6f2 are not working,but Unity 3D FREE is OK.

Androdi version:4.4  phone mode:xiaomi 1S

**Comment by smdol** [comment]
I've seen some other people report this same rendering problem in other forums.  Since it is Unity Pro, the problem is likely due to a RenderTexture issue.  It could be the specific format used in the Cardboard SDK (RGB565) is not supported on this phone.

**Comment by aviomaksim** [comment]
My app users reports about similar problem with version 0.4, but this problem disappears when app was updated to 0.5.

**Comment by nathanmartz** [comment]
AFAIK this was fixed in 0.5.2 if not earlier, so closing this.
