### ISSUE TITLE
disabling rotation impossible in new 0.6?

### ISSUE THREAD

**Issue by brianchasalow** [googlesamples/cardboard-unity#156]
My fix in the last SDK was to disable head rotation entirely because it was causing problems, and handle it myself...is that impossible as of the 0.6 SDK? I'd really prefer to use my own gyro support...

EDIT: never mind. the order of operations required in the new update changes the Screen.orientation when some scripts are fired, which had me thinking it was a Cardboard SDK issue. it's not.

**Comment by D3m0n92** [comment]
@brianchasalow  is too much to ask you to share your script to the management of the gyroscope? What the SDK actually does not work so well: /

**Comment by smdol** [comment]
I'm very interested in getting feedback on how the gyro tracking is working, so I have something specific to take to our sensor team.  Is it too jittery, too laggy, drift too much?  Any other details?  Thanks!
