### ISSUE TITLE
Cardboard audio system not work

### ISSUE THREAD

**Issue by dillon081818** [googlesamples/cardboard-unity#157]
i create a empty project and then import sdk and demo ,  the Console show : 

Cardboard audio system is initialized (Quality: Medium, Sample Rate: 44100, Channels: 2, Frames Per Buffer: 1024).

Failed to initialize spatializer. No plugin has been selected. Please check that the project audio settings and the plugin importer settings have been set up correctly.

Cardboard audio system is shutdown.

![qq20160126-0](https://cloud.githubusercontent.com/assets/4834203/12580654/39210b64-c46c-11e5-965a-b29c7f34dff2.png)

**Comment by nathanmartz** [comment]
You need to set the Audio Spatializer plugin for your project as described in our getting started doc: https://developers.google.com/cardboard/unity/guide#spatial_audio_for_vr
