### ISSUE TITLE
Option for programmatically change device profile.

### ISSUE THREAD

**Issue by ITurchenko** [googlesamples/cardboard-unity#158]
Can I ask about ability to programmatically change device profile without asking user to go to settings and scanning QR code? 

I tried to override method UpdateProfile in BaseCardboardDevice with custom values but nothing changed.

Or at least, can I somehow use Jun'14 version (which seems to be default for SDK 0.5)?

**Comment by nathanmartz** [comment]
You can set the DefaultDeviceProfile in Cardboard.cs. This will determine the default used for users. If they have already paired a viewer, however, this setting will have no effect. We do not intend to allow apps to programmatically override the actual viewer users have paired.
