### ISSUE TITLE
Wrong package format using AssetDatabase.ImportPackage

### ISSUE THREAD

**Issue by hannibalov** [googlesamples/cardboard-unity#16]
Hi,

I'm importing the package programmatically using AssetDatabase.ImportPackage (http://docs.unity3d.com/ScriptReference/AssetDatabase.ImportPackage.html) and it throws the following error:

"Error while importing package: Package has unknown format"

However, if I import the package manually using Assets->Import Package or double clicking it works fine. Also, if I export it myself and then import it through my script then all works fine too. It's quite strange. Not sure if this is a unity problem or version incompatibility, but it's the first time it has happened to me and I've worked with quite a lot of packages.

Thank you

**Comment by qwarnant** [comment]
Which version of unity3d editor do you have ?

**Comment by hannibalov** [comment]
I'm using 4.6.1

**Comment by hannibalov** [comment]
Tested in 4.6.2p1 and all works fine. 

It's a bit weird, but since it's now it's working I guess you can close the issue.

Thank you!

**Comment by LAOMUSIC** [comment]
I would like to propose a solution for this issue:
1. install Python [()](https://www.python.org/downloads/mac-osx/)
2. open Applications/Utilities/Terminal
3. type in python [(drag&dropt[PythonScrip])](https://github.com/gered/extractunitypackage)Here  drag&dropUnitypackageHere drag&dropDestinationFolderHere
4. be happy !
