### ISSUE TITLE
Can't load libvrunity.so (x86 android phone), can't load libaudiopluginvrunity.so

### ISSUE THREAD

**Issue by frconstruct** [googlesamples/cardboard-unity#160]
After upgrade from 0.5.2 to 0.6 libvrunity.so cannot be properly loaded by x86 android phone. The exact error thrown:
`Couldn't open /data/app-lib/[app-identifier]/libvrunity.so, error: dlopen failed: "data/app-lib/[app-identifier]/libvrunity.so" has unexpected e_machine: 40`
The same applies to libaudiopluginvrunity.so. On the arm phone libvrunity.so works just fine, though libautiopluginvrunity.so still cannot be loaded.

Tested on a fresh project with just SDK and demo scene imported

Using 0.5.2 libvrunity.so with the rest from 0.6 results in everything working except SetUILayerEnabled (as it is not available in 0.5.2 version of lib obviously).

EDIT:
I've just built a demo app with x86 version of libvrunity.so marked as ARMv7 compatible and tested it on ARM phone - it worked. Did you by chance posted the arm version of libvrunity.so in the x86 directory and marked it as x86?

**Comment by smdol** [comment]
We just tried to repro with the SDK + demo in a new project on an x86 device and it ran OK.  We must be missing a factor that is affecting you.  Would you be able to share your fresh SDK + demo scene project that shows the problem?  

Also, can you say which phone and version of Android you are using?

**Comment by frconstruct** [comment]
Sure. Here it is: [link](https://drive.google.com/file/d/0B3QD2PSx98QFUF9oTG1ZTlhWbmM/view?usp=sharing)

There is really nothing special to it though - New project, import SDK, import demo scene, add demo scene, build and run.

As for the x86 phone, it is Asus Fonepad Note 6, android 4.4.2 .
The ARM phone is LG Nexus 4, although I can't check its android version right now.

**Comment by nathanmartz** [comment]
Thanks for the project. One more question. What version of Unity are you using?

**Comment by frconstruct** [comment]
I've tried on both unity 5.2.3 and 5.3.2. The most interesting part for me is how did I manage to run this demo on nexus 4 with x86 version of libvrunity.so marked as ARM compatible.

**Comment by samboyer276** [comment]
I'm having the same issue here...
I've only recently jumped onto the Cardboard bandwagon, so I've only been using version 0.6 of the Unity SDK. I have the exact same error, but it may be worth mentioning that libaudiopluginvrunity.so cannot load, as well as libvrunity.so.
The build works fine on an ARM Android device, but not on an x86 device. Using version 0.5.2 of the SDK works fine.

**Comment by minglei-afterworkapps** [comment]
I'd the same issue. In the v0.6 SDK, under the Android/lib folder, it seems armeabi-v7a/libvrunity.so and x86/libvrunity.so are exactly the same binary. @smdol - do you know if it is intended or if there is a packaging error?

**Comment by nathanmartz** [comment]
It's a bug. We'll fix in the next update. Sorry!

**Comment by minglei-afterworkapps** [comment]
Thanks for confirming. Could you please post the x86 binary on github, so we don't have to wait for a release. We just updated to v0.6 and it is blocking our releasing schedule. Really appreciate it.

**Comment by liyonghelpme** [comment]
i test it in mac with unity 5.3.4 and android (api23) intel atom x86 emulator, can't load vrunity.so too

**Comment by smdol** [comment]
@liyonghelpme  Which version of the SDK are you using?

**Comment by vancesouders** [comment]
We're seeing the same thing here.  Simple Unity application and the demo scene crashes on start with logcat reporting "Unable to find libaudiopluginvrunity".  Building with the latest plugin from Github (0.7.2), Unity 5.3.4f1 and testing on an Asus Zenphone 2 (Android 5.0.2).

**Comment by anokta** [comment]
@vancesouders Just tried to reproduce the issue with the same setup and it ran OK. Two things you might want to double-check to see if you still get the same issue:
1) Have you tried running it with a fresh SDK + demo scene project?
2) Did you set the Spatializer Plugin to "CardboardAudio Spatializer" in Unity -> Edit -> Project Settings -> Audio?

**Comment by BlackDragonBE** [comment]
@anokta   
I had the same problem and setting the Spatializer Plugin as you described fixed it!
Thanks.
