### ISSUE TITLE
Failed to load 'Assets/Plugins/x86_64/audiopluginvrunity.dll'

### ISSUE THREAD

**Issue by Hrusilov** [googlesamples/cardboard-unity#161]
I have Unity 5.3.2f1 and Cardboard v0.6
Even with a new clean Unity project just imported Cardboard SDK and Demo I get this error (app. 5 times):
"Failed to load 'Assets/Plugins/x86_64/audiopluginvrunity.dll' with error 'The specified module could not be found.
', GetDllDirectory returned ''. If GetDllDirectory returned non empty path, check that you're using SetDirectoryDll correctly."

In project setting I don't have an option to choose Cardboard Spatial audio, just None.

Am I doing something wrong? Do I need to enable something else?

Thanks

EDIT: when deplayoed to android device the sound is working. so the problem is with the x86_64 version probably...

**Comment by nathanmartz** [comment]
Hi. We're not able to repro here. Do you get that Failed to load error in the Editor console or when you build an app? What OS are you running? What platform are you targeting?

Also, it's very suspicious that you are not seeing Cardboard Spatial Audio in the Audio Project settings. That means something almost certainly is wrong.

**Comment by Hrusilov** [comment]
I get that fail in the Editor as soon as I import the SDK package and again when I try to run the demo in Editor. I can run the demo in editor but without any sound. I can build it for Android and also for Windows (x86 or x64). When I run the build on Android or Windows with x86 build I can hear the sound. When I run the build in x64 verson or in Editor I don't hear any sound. Since I have Win 7 x64 it seems that the x86_64 version of the dll is doing the problem.
My system: Windows 7 SP1 x64
Mainly I am targeting Android but planning also build for PC.
What bugs me most ist the editor since I can't try any sound or music in Editor

**Comment by nathanmartz** [comment]
Thanks for the information. The core problem is that the dll isn't loading, which is why you can't see the dropdown in the Editor.

We are testing on a Win 7 x64 machine using the same version of Unity and unfortunately can't repro. Clearly there is something subtly different on your machine than our test machine. Do you have Visual Studio installed by any chance? We're wondering if the issue is some sort of vc_redist related problem.

Lastly, just to sanity check, you do have the file Assets/Plugins/x86_64/audiopluginvrunity.dll right?

**Comment by Hrusilov** [comment]
Yes the plug-in is there :)
Problem solved. I omitted to install Visual Studio before. So I re-installed it and this time I included VS and everything is working.
Thanks for the support

**Comment by baroquedub** [comment]
I have the same problem, but I do have Visual Studio installed (although from a separate installation).

File is there in  Assets/Plugins/x86_64/audiopluginvrunity.dll 

Apparently compiles ok, and sound does play on the mobile device.

Same system Win7 x64

Any chance of getting this reopened, or do I need to log another issue?

**Comment by ognjenmarcheta** [comment]
Hi i have same problem on my macbook pro. Unity 5.3.1f1. cardboard sdk v0.6
Btw on windows machine it's working fine without any problem.

"DllNotFoundException: audiopluginvrunity"

Is there any workaround for this problem?

**Comment by ianholing** [comment]
Same problem here using Unity for Linux 5.4.0b13

"DllNotFoundException: audiopluginvrunity"

**Comment by nathanmartz** [comment]
We don't support Unity Editor for Linux as it's still experimental.

**Comment by Tommislav** [comment]
Same problem for me on a Windows 10 machine. Cannot load dll, even though it's there.

**Comment by shahzadchaudary** [comment]
Hi everyone,

I am facing the same issue using Unity 5.3.0f4 (64 bit), WIndows 8.1 Pro 64-bit. Facing issue while loading/running project in Unity editor. It is working fine on Android phones though.

Please help omit this error.


Thanks

**Comment by sourabh10995** [comment]
Same problem with windows 10. Any fix out yet?

**Comment by MrDizzle** [comment]
I'm having this issue too, New MacBook Pro - Unity 5.4.0.b12

**Comment by TimothySPeterson** [comment]
Hey all,
If it helps, this is what I did to get mine working (Windows 10, Unity 5.3.4f1, Google VR SDK for Unity v0.8):
1. Close Unity Completely
2. Using the file browser, navigate to your projects: Assets\Plugins\
3. Delete the x86_64 folder (The only thing in this folder was the previous audioplugingvrunity.dll)
4. If you have x86_64.meta file, delete that too.
5. Open up your unity project and re-import the package.

At that point, it imported properly and was detected properly as well.

**Comment by fsereno** [comment]
Hi did anyone get a good solution for this issue ? I still have this issue. I am running this on a Mac with Xcode, and on Mountain Lion. I still get the error regarding audioplugingvrunity.dll not being loaded successfully. I am new to Unity so please explain any solution in as much detail as you can. 
I would really appreciate anyones help.

Many thanks

Fabio

**Comment by crowriot** [comment]
I'm on Windows 7 x64 and also had the same problem, turns out that I didn't have the the Visual Studio 2015 Redistributables installed on my system. 
Just installed them https://www.microsoft.com/en-us/download/details.aspx?id=48145 and the error is gone.

**Comment by niuk** [comment]
Try using [Dependency Walker](http://www.dependencywalker.com/) on the offending plugin. Ignoring the bunch of file not founds involving stuff like "API-MS-WIN-CORE", you might be able to see a few legitimately missing dlls.

In my case, the plugin could not find ucrtbased.dll, so after I installed the Windows 10 SDK according to [this post](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/), the plugin was able to load.

**Comment by barzorke** [comment]
Try to drop your dll onto the root of your unity project (next your Assets folder, not into)

**Comment by shubhiec1049** [comment]
Hi, I am also getting the same issue on Windows 7, below is the error description:
Plugins: Failed to load 'C:/Git/ar-vr-v1.0/Wiki_Latest/Library/PackageCache/com.unity.xr.windowsmr.metro@1.0.11/Plugins/x86_64/AudioPluginMsHRTF.dll' because one or more of its dependencies could not be loaded.

After deleting AudioPluginMsHRTF.dll , no error but not able to run the project.
Please suggest
