### ISSUE TITLE
Issue compiling on Xcode - Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by alamboley** [googlesamples/cardboard-unity#162]
Hey,

I've an issue building a Google Cardboard project for iOS. I've added the `Security.framework` in Xcode but when I compile I get:

Undefined symbols for architecture armv7:
"_setUILayerEnabled", referenced from:
      _CardboardiOSDevice_SetUILayerEnabled_m74253001_0 in Bulk_Assembly-CSharp_0.o
      _CardboardiOSDevice_setUILayerEnabled_m_1083931927_0 in Bulk_Assembly-CSharp_0.o
      _CardboardiOSDevice_SetUILayerEnabled_m74253001_0 in Bulk_Assembly-CSharp_0.o
      _CardboardiOSDevice_setUILayerEnabled_m_1083931927_0 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _CardboardiOSDevice_setUILayerEnabled_m_1083931927_0)  
  "_SetRoomProperties", referenced from:
      _CardboardAudio_SetRoomProperties_m1701032588_0 in Bulk_Assembly-CSharp_0.o
      _CardboardAudio_SetRoomProperties_m1701032588_0 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _CardboardAudio_SetRoomProperties_m1701032588_0)  
  "_CreateRoom", referenced from:
      _CardboardAudio_CreateAudioRoom_m_1903398240_0 in Bulk_Assembly-CSharp_0.o
      _CardboardAudio_CreateRoom_m_895253938_0 in Bulk_Assembly-CSharp_0.o
      _CardboardAudio_CreateAudioRoom_m_1903398240_0 in Bulk_Assembly-CSharp_0.o
      _CardboardAudio_CreateRoom_m_895253938_0 in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _CardboardAudio_CreateRoom_m_895253938_0)...

Any ideas?

**Comment by alamboley** [comment]
Ok so it seems I forgot to update the Plugin folder... My bad!

**Comment by dominik-theConstruct** [comment]
Hi,
I'm having the same issue.
Which folder did you update? The Unity plugin folder?
Can you explain more if possible.
I'm quite new to building iOS esp. from Unity.
Thanks,
Dominik

**Comment by renatoaloi** [comment]
Same here.
Solved by selecting appropriate build target for iOS when importing GVR library.
https://github.com/googlevr/gvr-unity-sdk
