### ISSUE TITLE
Please update the GoogleDesignLab project to unitiy 5.3 and XCode 7.2.

### ISSUE THREAD

**Issue by edusoft** [googlesamples/cardboard-unity#171]
Hi! Excelent work! 
Recently I downloaded and tested the famous sample GoogleDesignLab,
I saw the documentation and you recommended use Unity 4.9.5 but I think that is not compatible with XCode 7.2..   Did you test it?

However... :)

I tested it with the lastest version of unity (5.3.2) and xcode (7.2) and  these are the results:

1) The Unity project works fine, compile, simulate, all is excelent.
2) But when I build the unity project to iOS, the project build successfully (after some low issues) but after deployed to mi Iphone 6S, the application is opened and I only see the the google cardboard frame (with the setting menu in the middle) and a black background.

Did you find some workaoround?

**Comment by nathanmartz** [comment]
That documentation item is out of date. The CardboardDesignLab project here on github is actually from Unity 5.3. 

I'm not aware of the iPhone 6S issue, but we'll look into it and get back to you.

**Comment by edusoft** [comment]
For that reason the project works well in Unity!
May be the problem is with XCode 7.2...

I eagerly await your tests... :)

**Comment by grobm** [comment]
Simple issue, update the paths and disable the bitcode on build. Should work.

**Comment by edusoft** [comment]
Hi! I already disable the bitcode for these reason the build is successfully, but..... Sorry I don't understand the "update the paths"... which paths?

**Comment by edusoft** [comment]
Any News?

**Comment by edusoft** [comment]
Solved!!!!
I found the solution! 
http://stackoverflow.com/questions/30940544/xcode-google-cardboard-build-failure

Thanks!
