### ISSUE TITLE
Change the Settings and Arrow texture

### ISSUE THREAD

**Issue by nosmirck** [googlesamples/cardboard-unity#174]
Hi, I'd like to know if there is a way to change the texture for the arrow (back button) and the gear (settings button) when on VR mode for Android and iOS.

Thanks for any help!

**Comment by nathanmartz** [comment]
These are intentionally standardized to be the same across all apps. If you could make changes, what would you want to change?

**Comment by nosmirck** [comment]
Hi @nathanmartz Thanks for replying.

I would like to change the back and the settings icons with some of our design to match the general design and "fell & look" of the app.

Not so big changes, but, they would look good for the app we are building.

How can I achieve this?

**Comment by nathanmartz** [comment]
Thanks for the info. Our current design is intended to ensure that users always know what those affordances look like and where they are, so we don't currently or plan to expose ways for titles to customize them.

**Comment by Rubinhuang9239** [comment]
"Our current design"...That's not even a design...
