### ISSUE TITLE
SDK 0.6 - samsung galaxy tab 4 smt530 - camera no moving

### ISSUE THREAD

**Issue by AleR3ds** [googlesamples/cardboard-unity#175]
Hi, i test the vr app sample cardoboard demo without stereo cam, on my tablet, but camera not moving when i move the tablet. When start app camera have a bad orientation and don't move.

Thanks

Ale

**Comment by AleR3ds** [comment]
Ok sorry, maybe that in this tablet there is not the gyroscope... :(

Ale

**Comment by nathanmartz** [comment]
Yes. That is the problem.
