### ISSUE TITLE
Head Tracking and View inverted

### ISSUE THREAD

**Issue by JoelBradley** [googlesamples/cardboard-unity#177]
Hi
I'm using SDK v0.6 and Unity v5.3.2.
When I run the demo on my Nexus 5 the view is upside down, with the floor above me and the sky below me. When I look up I look to the floor and the left to right is also flipped.
Thanks in advance for a fix or solution.

**Comment by grobm** [comment]
Are you forcing the orientation? Try switching the Orientation from Right Landscape to Left Landscape.

**Comment by JoelBradley** [comment]
Ah yes, that was the problem. Thank you very much!
