### ISSUE TITLE
Not able to scan QR code from my App (iOS)

### ISSUE THREAD

**Issue by justinwasilenko** [googlesamples/cardboard-unity#179]
I have a user trying to scan a QR code for their Cardboard headset on iOS using a iPhone 6.

Scanning using the official Cardboard they said worked. But when trying to scan the code using my app they just have a black screen and aren't able to scan the code.

Attached below is a picture:

![unnamed](https://cloud.githubusercontent.com/assets/11709400/13296861/d87f835a-db2f-11e5-81bc-e3f0005156fe.jpg)

They user tried uninstalling both my app and the Cardboard app, with no success.

**Comment by smdol** [comment]
Looks like the dialog is working but no camera image is coming through.  Is it possible they accidentally hit the wrong button when iOS asked for permission to use the camera?

**Comment by justinwasilenko** [comment]
This was indeed the problem, thanks!
