### ISSUE TITLE
Crash during scene transition with Magnetic Trigger

### ISSUE THREAD

**Issue by monizka** [googlesamples/cardboard-unity#190]
I have found that Crash is occurring when I try to use Magnetic Trigger for scene transition in Galaxy Note 4. It does not happen when I use touch input, and I have tested on Galaxy S6 Edge without any problem.

Have any idea about?
I am using Unity 4.6.1 and Cardboard 0.6 for this project.

**Comment by SisadaR** [comment]
There are a few issues about this problem. 

I'm waiting for the fix to be released as well

**Comment by smdol** [comment]
This bug was fixed in the v0.7 release of the SDK.
