### ISSUE TITLE
Crash when unity loadlevel()

### ISSUE THREAD

**Issue by Yao2itch** [googlesamples/cardboard-unity#194]
I use the google's unity activity to startup application, however it crashes when press system back button? Dose anyone have the same problem? and how to solve it.

**Comment by handyface** [comment]
In the latest Unity Loadlevel is obsolete. Try replacing it with SceneManager.LoadScene(). If that's not the problem, please provide us with more information.

**Comment by smdol** [comment]
Are you using a V1 Cardboard (with magnet)?  That causes a crash on loadlevel due to a threading issue.  There is a separate bug on this site about that.  Fix is coming.

**Comment by tachen** [comment]
Try override the UnityPlayer kill() function, the function will kill the process！

UnityPlayer.class
protected void kill()
  {
    Process.killProcess(Process.myPid());
  }

**Comment by Yao2itch** [comment]
@smdol i use mojing，a glass made by a chinese company.

**Comment by Yao2itch** [comment]
![default](https://cloud.githubusercontent.com/assets/17959579/13985183/39f59630-f136-11e5-9b2b-718ef41dae91.jpg)
This is the bug. Anyone meet the similar situation?

**Comment by smdol** [comment]
Are you trying to exit the app because of a back button press, and the crash is happening there?

**Comment by Yao2itch** [comment]
@smdol Actually, i make an android project, and export a unity project. The android will startup the unityactivity, I try using back button to quit unity application. However the app crashes.

**Comment by smdol** [comment]
Oh, I see.  There is a function on our Activity listener Java class called "finishActivityAndReturn" that might help with this situation.  You would call it rather than calling Application.Quit().  Look in the script CardboardAndroidDevice.cs to see how to call functions on the activity listener.
