### ISSUE TITLE
Any plans for Adobe Air sdk?

### ISSUE THREAD

**Issue by Nikos-Laskaridis** [googlesamples/cardboard-unity#198]
Adobe Air is a popular platform for mobile games and apps with a powerful 3d engine, it would be great to have an SDK for cardboard instead of creating everything from scratch.

**Comment by nathanmartz** [comment]
Hi, Nikos. That's actually a good question for Adobe. Due to the way that platform works and the way it's licensed, they would need to integrate our SDK and not the other way around.

**Comment by Nikos-Laskaridis** [comment]
Thanks for answering, nathanmartz. Adobe has a system of adding external components called ANE (Adobe Native Extensions), where anyone who wishes can write external code (I think in javascript)  to make native calls. I was hoping for something like that since I believe it's technically possible.
