### ISSUE TITLE
Carboard SDK & demo cause fast cpu heating 

### ISSUE THREAD

**Issue by chq1314** [googlesamples/cardboard-unity#199]
Carboard SDK & demo cause fast cpu heating 
What do you think??

**Comment by chq1314** [comment]
If the distortion is closed, the heat will reduce a lot of

**Comment by nathanmartz** [comment]
Yes, that is correct. Rendering at a high framerate at high res with distortion can be expensive. You can look into rendering at a lower rate, or using [vertex distortion](http://gamasutra.com/blogs/BrianKehrer/20160125/264161/VR_Distortion_Correction_using_Vertex_Displacement.php).
