### ISSUE TITLE
Importing into project errors

### ISSUE THREAD

**Issue by zfarm** [googlesamples/cardboard-unity#20]
Any idea's why I would be getting this when trying to build? 

 Temp\StagingArea\libs\armeabi-v7a\libRenderingPlugin.so already exists

**Comment by smdol** [comment]
If you upgraded the plugin in an existing project, make sure remove some old files in the Plugins/Android from the previous version.  See the release notes:
    https://developers.google.com/cardboard/unity/release-notes

libRenderingPlugin.so is one of them.

(Unity does not remove old files when importing an updated package.  It just overwrites existing ones and add new ones.)

**Comment by zfarm** [comment]
Nice.. Thanks should have double checked that.

**Comment by zfarm** [comment]
Click on the link below to open the message in a browser:
http://mandrillapp.com/track/click/30119679/shoutout.wix.com?p=eyJzIjoiV3VVb0twbjNUOExKaFA0RGozbUNmMVhEcl9VIiwidiI6MSwicCI6IntcInVcIjozMDExOTY3OSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvc2hvdXRvdXQud2l4LmNvbVxcXC9zb1xcXC9kS2xySWZpYj9jaWQ9MmUwNjJjMmQtYzczMS00NjNjLWE3MjMtMmRjM2RjYjZjYzYxXCIsXCJpZFwiOlwiMTY3NDcxZTRmODBiNDY5OTk3ZDYzMDgyZGQ1MDNhMGFcIixcInVybF9pZHNcIjpbXCI1MWNkZjgwNzNmMGEyZGVjMTNiNGJiMmVlOWYzOWIxYjdmZjBkMjJkXCJdfSJ9

You've received this email because you are a subscriber of http://mandrillapp.com/track/click/30119679/www.goshow.info?p=eyJzIjoibkg3NEJnckl0RWdVenM4bEVPYU5QUFRwTlk0IiwidiI6MSwicCI6IntcInVcIjozMDExOTY3OSxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvd3d3Lmdvc2hvdy5pbmZvXFxcL1wiLFwiaWRcIjpcIjE2NzQ3MWU0ZjgwYjQ2OTk5N2Q2MzA4MmRkNTAzYTBhXCIsXCJ1cmxfaWRzXCI6W1wiOGI0OWZhZWJkNGVkYjlkMzdkNDU0ZDZiMjQ0MmM2MTI1YmY2MTBhMVwiXX0ifQ.
If you feel you received it by mistake or wish to unsubscribe, click http://www.wix.com/my-account/contacts/unsubscribe?siteName=goshow&metaSiteId=131d786d-a6a5-1a05-a05a-8f7cc3d3a862&unsubscribeToken=abcefd4d5885911e7f4ea863ecce180388e169a39e4c714f1a99cb3376c2b7062320dd874b3f4d4c360569a244bdb768664f679084691795a68ba7bc1a39018620f897be5a004209cb14cb949b511978445fe65559299dd1ed48d4aea7087f26cc895ae8afb3420cb44759fa5eaf78726b50be6f450c1d38f64bee656d51b50baa806aca2088f6f1259eafa21d7e2cf2caab51885ce5f30e56805bf8db9fc8c69f55360d85f5bfcda815f044549a0fa6a256ae45643e643b4bd7753cd9b315c8cceb611387335ecfbc04e3d674c5525bc95bd347945c9cae3470117189dc477e3e0042cd9ac2b3aa19e786638031c9584494ac0f5a511cfca1b40ddc72c7ea4e06b2839b7083bd52f131ce74020427a28b5b60d082f2f0b6504a5afbcb775f9144a8bfc0547bcb6fa6c2b50f0a236af56f3711393bc8e2446e67b313ac793bd12620b1587e0aa257a623c65bd55c02a978986a980b9554b01395a92b32e26a308198edf4a1b89be40d2000aa0b6f09b3.
