### ISSUE TITLE
TrackRotation

### ISSUE THREAD

**Issue by semangu** [googlesamples/cardboard-unity#201]
I can't access to CardboardHead Script(Form other JavaScript script) to disable TrackRotation in a game?

Anybody know how i can access it in javascript?

**Comment by smdol** [comment]
The order Unity compiles scripts in means you can't call from JavaScript to C#.  A workaround is to move C# scripts into the "Standard Assets" directory (which normally gets created when you import Unity assets like skyboxes, image effects, etc).  C# scripts in there are compiled early.
