### ISSUE TITLE
Buildplattform Windows/OSX

### ISSUE THREAD

**Issue by doofmars** [googlesamples/cardboard-unity#210]
Quick question: Is it possible to build the Cardboard app for Windows/OSX?

For a presentation I want to display the "view" of the user on a bigger screen.
To achieve this I wrote a script to establish a socket connection and send camera-rotation-information from Android to a Windows machine. This works like a charm in the Unity IDE.
However when I try to set windows as Build target the skybox is not rendered and the on-screen developer-console throws many NullReferenceExceptions. Same behaviour on OSX and Linux. I cant debug into the build application to see where this Exeption occurs.

I could remove the Cardboard-Plugin for the Windows build but then the Cardboard features Gazed At and pointer are missing.

**Comment by smdol** [comment]
Look in BaseVRDevice.cs, at the bottom.  For your case, you might get it to work by making that code choose the UnityEditorDevice for Windows and OSX platforms.

**Comment by doofmars** [comment]
Thank you very much for pointing me in the right direction!
I solved/enabled the stand-alone build by creating a new StandaloneDevice and extending the preprocessor in the Cardboard.cs.
Now the build is working as intended.

**Comment by fullace1** [comment]
I'm struggling to solve this problem. Can you explain more how to modify Cardboard sdk for another platform like windows?

StandaloneDevice.cs, BaseVRDevice.cs

**Comment by doofmars** [comment]
This is a unofficial mod, no support if something breaks :-P

first create a custom StandaloneDevice.cs I based mine on the UnityEditorDevice.cs
but removed some editor stuff you can find my version here: http://pastebin.com/Ei9gP0JT
Just place it inside of \Assets\Cardboard\Scripts\VRDevices

Second add some references to StandaloneDevice

in **\Assets\Cardboard\Scripts\Cardboard.cs** change line **286** from
**#if UNITY_EDITOR**
to
**#if (UNITY_EDITOR || UNITY_STANDALONE)**

in **\Assets\Cardboard\Scripts\VRDevices\BaseVRDevice.cs** add the elseif to the if clause in line **269**
**#elif UNITY_STANDALONE
      device = new StandaloneDevice();**

this should be it... Hope it works

**Comment by fullace1** [comment]
doofmars, Really Warmly Thank you. It is solved!
