### ISSUE TITLE
CardboardBundle.SDK String bundles not loaded correctly on our iOS app

### ISSUE THREAD

**Issue by apollow** [googlesamples/cardboard-unity#214]
Going to need some trouble shooting on this one:

We are having troubles getting the correct localized strings loaded up on the Cardboard side of our app: 

![img_0247](https://cloud.githubusercontent.com/assets/2719085/14995237/92fa34ae-1128-11e6-91d3-635199f4e777.jpg)

I made a little test to see if they are properly within our app:

```
let bundleID = NSBundle.mainBundle().pathForResource("CardboardSDK", ofType: "bundle")
let b : NSBundle = NSBundle(path: bundleID!)!
let cardboardStrs = b.pathForResource("CardboardSDK", ofType: "strings")!
let dict : NSDictionary = NSDictionary(contentsOfFile: cardboardStrs)!
for item : String in dict.allKeys as! [String] {
    print ("\(item) : \(dict[item]!)")
}
```

Which outputs:
```
PlaceYourPhoneInCardboard : Place your phone into your Cardboard viewer.
CanNotFindSymbol : Can't find this symbol?
ParsingFailed : Problem in parsing the Url
InvalidQRCode : The QR code is invalid
DefaultViewerName : Default viewer
SwitchViewer : SWITCH
SettingsSyncLabel : Sync with Google Cardboard
BackButtonLabel : Back
LoadingMessage : Parsing configuration data
PlaceYourPhoneInViewerFormat : Place your phone into your %1$@ viewer.
SettingsCurrentViewerLabelFormat : Current viewer: %1$@
DifferentViewerQuestion : Using a different viewer?
FindSymbolOnViewer : Find this symbol on your viewer
DataSynced : %1$@ detected
OnboardingIntroLine1 : Let's get you set up
SkipButtonLabel : SKIP
OnboardingIntroLine2 : Pair your phone with your viewer for the best experience.
NavTitleLabel : QR Scan
TroubleShootingTips : Troubleshooting Tips
OnboardingNoViewerPrompt : No cardboard viewer?
SettingsNavTitleLabel : Settings
OnboardingGetCardboardButton : Get One
```
(Interesting to note that "HelpActivityMenuTitle" and "SwitchViewerActivityMenuTitle" are not shown in the output)

Problem is is we do not internal access to change the strings, is there any way to alter the strings shown in the screenshot or to make sure those strings load up the CardboardSDK.Bundle/en.lproj/CardboardSDK.strings file properly?

**Comment by apollow** [comment]
Very odd. The code was actually picking it up in a different strings file entirely:

CardboardSDK.bundle/Resources/en.lproj/CardboardSDK.strings not
CardboardSDK.bundle/en.lproj/CardboardSDK.strings.

Having added the strings from the one in en.lproj to CardboardSDK.bundle/Resources/en.lproj/CardboardSDK.strings, it works now.

Leaving this open for now, close if necessary.

**Comment by smdol** [comment]
Did you upgrade the SDK in this project?  I think the file moved, so you would have had both the old location and new location in your project.  (Unity tends to do this on package upgrades.  It's a good idea to clean out the old package manually before upgrading.)

**Comment by apollow** [comment]
This must be the reason, I think cleaning out the bundles would be a good idea on next iteration. Closing then.
