### ISSUE TITLE
CardboardAudioSource.cs, UnityEngine.AudioSource doesn't contain spatialize definition

### ISSUE THREAD

**Issue by Zekard92** [googlesamples/cardboard-unity#218]
Assets/Cardboard/Scripts/Audio/CardboardAudioSource.cs(286,21): error CS1061: Type `UnityEngine.AudioSource' does not contain a definition for `spatialize' and no extension method `spatialize' of type `UnityEngine.AudioSource' could be found (are you missing a using directive or an assembly reference?)

same on SetSpatializerFloat.

**Comment by nathanmartz** [comment]
What version of unity are you using? The SDK requires 5.2 or higher.

**Comment by Zekard92** [comment]
unity 5.1.1f1 personal
