### ISSUE TITLE
Unity Arduino Cardboard

### ISSUE THREAD

**Issue by bamboofx** [googlesamples/cardboard-unity#22]
I convert my app from unity and arduino to cardboard using arduino with bluetooth as joystick controller.
In my first app without cardboard, bluetooth connection latency  form arduino to mobile very fast, but when i use CardboardMain prefab as MainCamera and publish app the bluetooth connection latency too slow. i don't know why and how to fix it. I think gyro sensor and accelerometter sensor slow down the bluetooth connection.

**Comment by izztti** [comment]
hi, i try to connect my arduino with which has a bluetooth module on it with unity.
and so far i am not capable to it.
can you help me to connect arduino with a unity project which runs on android?
thanks.

**Comment by D3m0n92** [comment]
Same here!

**Comment by bamboofx** [comment]
@izztti  try this https://www.assetstore.unity3d.com/en/#!/content/16467, or https://github.com/akexorcist/Android-BluetoothSPPLibrary and port as Unity Android Plugins

**Comment by nathanmartz** [comment]
Not really a cardboard specific issue, so closing the thread.
