### ISSUE TITLE
Demo Scene not displaying right on Samsung S7 Edge

### ISSUE THREAD

**Issue by gabgren** [googlesamples/cardboard-unity#220]
Hi !

The Demo Scene is working properly on my Nexus 6P but comes out very wrong on the Samsung S7 Edge. Is this a known issue? Or are only Nexus devices supported?

Here's a screenshot of how it outputs
![screenshot_20160516-215023](https://cloud.githubusercontent.com/assets/1724721/15293054/20a1f8ac-1b54-11e6-90e7-a6661c064280.png)

Thanks !

**Comment by smdol** [comment]
In the Build Settings, make sure you set the default orientation to
Landscape Left.

**Comment by gabgren** [comment]
Thank you, that was it
