### ISSUE TITLE
All white screen after splash

### ISSUE THREAD

**Issue by jamiltron** [googlesamples/cardboard-unity#24]
I am running Unity 5.0.0f4 and the cardboard-unity 0.4.5.

I have tried creating a basic scene with a plane, and pull in the CardboardMain prefab from the Cardboard/Prefabs folder, I can run fine in the editor, but when I try running it on my device (Nexus 5 running Android 5.1) I get the initial splash screen, followed by a completely white screen.

I have also tried running the DemoScene after removing references to CardboardGUI, but then I only get the Unity splash screen, which never updates.

Any help is greatly appreciated!

**Comment by smdol** [comment]
So far the best workaround that had been found, until this big is chased
down, is to enable the Development Build option in the Build dialog.
Please try that and say if it helps or not.

**Comment by smdol** [comment]
New version 0.4.9 is out.  See if it helps -- you may still need the Development Build option.

**Comment by jggiles** [comment]
Enabling the Development Build option fixed this for me on 0.4.9. Thanks!

**Comment by jamiltron** [comment]
Yes, unless I am mistaken I still need the development build option checked in 0.4.9

**Comment by PrototypeNM1** [comment]
In a simple scene with only the default Cube and CardboardMain GameObjects I was able to recreate this bug whenever the camera faced the Cube - otherwise it rendered the default skymap like normal.

Changing the Cube's Material from Default-Material to Default-Diffuse fixed the issue.

**Comment by mahdijeddi** [comment]
I could solve this by un-checking DirectRender on the StereoController script on the MainCamera.

**Comment by PrototypeNM1** [comment]
I'm guessing this bug relates to Unity depreciating the legacy shader system, changing all default materials to physically based materials in Unity 5.

**Comment by smdol** [comment]
Definitely the new Default-Material seems to trigger the bug more readily.

**Comment by smdol** [comment]
Unity fixed this in 5.1, it appears.
