### ISSUE TITLE
uGUI Overlay Canvas Support

### ISSUE THREAD

**Issue by NVentimiglia** [googlesamples/cardboard-unity#31]
Support for the new unity gui system and an overlay canvas would be nice. Currently my work around is to place the canvas in my game and to position it in front of the cardboard. My solution does not work very well and I end up with two version of my UI.

**Comment by smdol** [comment]
There's a GazeInputModule script in the project that works with uGUI, but
it needs a worldspace canvas in order to render in stereo.

-- Scott

**Comment by NVentimiglia** [comment]
I was able to get it to work, thanks.
