### ISSUE TITLE
Problem with LG optimus g 4.4.2

### ISSUE THREAD

**Issue by futer24** [googlesamples/cardboard-unity#32]
Hi 

I have the following screen problem:

https://www.dropbox.com/s/bwkgzeg0v23aszh/boxeovr.png?dl=0

With:
- Unity 5.0.2f1 Personal
- Cardboard sdk v0.4.10

thks in advance!

**Comment by smdol** [comment]
Can you check with v0.5 of the Cardboard SDK?  It has some changes that will hopefully fix this.

**Comment by ngandtt** [comment]
Still crash in LG optimus :(

**Comment by nathanmartz** [comment]
Closing old issues. Likely fixed in newer versions of Unity and the SDK.
