### ISSUE TITLE
SDK 0.5 internet permission?

### ISSUE THREAD

**Issue by LegACy99** [googlesamples/cardboard-unity#33]
On AndroidManifest.xml
```
<uses-permission android:name="android.permission.INTERNET" />
```
Is there any reason for the internet permission line in the Android manifest? May be like the app can load the viewer spec from the internet?

I'd like to remove that permission from my manifest (since it would be weird to have an app that features no online functionality whatsoever to request internet connection), but I'm afraid it could cripple some random feature I don't know.

**Comment by smdol** [comment]
It can be removed safely.

**Comment by smdol** [comment]
It has been commented out in v0.5.1.
