### ISSUE TITLE
Have a problem with Optimus G (L-01E), Android Ver. 4.1.2.

### ISSUE THREAD

**Issue by Nitro888** [googlesamples/cardboard-unity#34]
Have a problem with Optimus G. previous version had a no problem.

HW : optumus G (L-01E)
Andoid : 4.1.2
Unity3d : 5.0.2f1 personal
Cardboard sdk : 0.5

05-29 16:44:01.445  12471-12471/com.example.CardboardUnityDemo I/Unity﹕ windowFocusChanged: true
05-29 16:44:01.455  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 4, Memory = 1816mb
05-29 16:44:02.265  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ [SHA1] 05f0c014c16a8a06257948c018f6792bb3a90b94   21489687 bytes ~ lib/armeabi-v7a/libunity.so
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ [SHA1] 24b169a7ce40726755333dfb3696ef059df04cba   24936126 bytes ~ lib/x86/libunity.so
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Mono path[0] = '/data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed'
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Mono config path = 'assets/bin/Data/Managed'
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ PlayerConnection initialized from /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data (debug = 0)
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ PlayerConnection initialized network socket : 0.0.0.0 55320
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ PlayerConnection initialized unix socket : Unity-com.example.CardboardUnityDemo
05-29 16:44:03.036  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Multi-casting "[IP] 0.0.0.0 [Port] 55320 [Flags] 2 [Guid] 3299062717 [EditorId] 4245193351 [Version] 1048832 [Id] AndroidPlayer(LGE_L-01E@0.0.0.0) [Debug] 0" to [225.0.0.222:54997]...
05-29 16:44:03.186  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ InitializeMonoFromMain OK (5cb48ee0)
05-29 16:44:03.186  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ PlayerConnection already initialized - listening to [0.0.0.0:55320]
05-29 16:44:03.216  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ PlayerInitEngineNoGraphics OK
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo I/Adreno200-EGL﹕ <qeglDrvAPI_eglInitialize:269>: EGL 1.4 QUALCOMM build:  (CL3243160)
    Build Date: 02/06/13 Wed
    Local Branch: GK_LGE_JB_2.2_RB2_AU130
    Remote Branch:
    Local Patches:
    Reconstruct Branch:
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ [EGL] Request: ES2 RGB0 000 0/0
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo W/Adreno200-EGL﹕ <qeglDrvAPI_eglGetConfigAttrib:481>: EGL_BAD_ATTRIBUTE
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo W/Adreno200-EGL﹕ <qeglDrvAPI_eglGetConfigAttrib:481>: EGL_BAD_ATTRIBUTE
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo W/Adreno200-EGL﹕ <qeglDrvAPI_eglGetConfigAttrib:481>: EGL_BAD_ATTRIBUTE
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ [EGL] Selected: ID[1] ES2 RGB16 565 0/0
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ [EGL] Request: ES2 RGBA32 8888 0/0
05-29 16:44:03.236  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ [EGL] Selected: ID[4] ES2 RGBA32 8888 0/0
05-29 16:44:03.286  12471-12486/com.example.CardboardUnityDemo I/Adreno200-C2D﹕ <c2d_wrapper_init:132>: C2D2 initializing a3xx version: libc2d2_a3xx.so
05-29 16:44:03.286  12471-12486/com.example.CardboardUnityDemo I/Adreno200-C2D﹕ <c2d_wrapper_init:196>: C2D2 wrapper initialized successfully
05-29 16:44:03.286  12471-12486/com.example.CardboardUnityDemo I/Adreno200-C2D﹕ <c2d_cmd_res_init:104>: Allocate CMD Buffer Address  0x5cfdf000 0x1009a000
05-29 16:44:03.326  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ ANativeWindow: (1280/720) RequestedResolution: (0/0) EGLSurface: (1280/720)
05-29 16:44:03.336  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Renderer: Adreno (TM) 320
05-29 16:44:03.336  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Vendor:   Qualcomm
05-29 16:44:03.336  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Version:  OpenGL ES 2.0 V@6.0 AU@  (CL@3243160)
05-29 16:44:03.336  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ GLES:     2
05-29 16:44:03.336  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ GL_EXT_debug_marker GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program_binary GL_OES_packed_depth_stencil GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM_writeonly_rendering GL_EXT_sRGB
05-29 16:44:03.346  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Creating OpenGLES2.0 graphics device
05-29 16:44:03.346  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ InitializeGfxDevice OK
05-29 16:44:03.346  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Initialize engine version: 5.0.2f1 (0b02744d4013)
05-29 16:44:03.427  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Begin MonoManager ReloadAssembly
05-29 16:44:03.447  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/UnityEngine.dll (this message is harmless)
05-29 16:44:03.447  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Loading /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/UnityEngine.dll into Unity Child Domain
05-29 16:44:03.517  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
05-29 16:44:03.527  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Loading /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
05-29 16:44:03.527  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/Assembly-CSharp.dll (this message is harmless)
05-29 16:44:03.527  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Loading /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
05-29 16:44:03.537  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/UnityEngine.UI.dll (this message is harmless)
05-29 16:44:03.537  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Loading /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
05-29 16:44:03.547  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/UnityEngine.UI.dll (this message is harmless)
05-29 16:44:03.547  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Loading /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/UnityEngine.UI.dll into Unity Child Domain
05-29 16:44:03.597  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ - Completed reload, in  0.173 seconds
05-29 16:44:03.607  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ PlayerInitEngineGraphics OK
05-29 16:44:03.607  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Found 13 native sensors
05-29 16:44:03.617  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Sensor :        Accelerometer ( 1) ; 0.001190 / 0.01s ; LGE Accelerometer Sensor / InvenSense
05-29 16:44:03.617  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Sensor :        Accelerometer ( 1) ; 0.001190 / 0.01s ; LGE Accelerometer Sensor / InvenSense
05-29 16:44:03.647  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Requested framebuffer: resolution[1280x720], rgba[8/8/8/8], depth+stencil[on], samples[0]
05-29 16:44:03.647  12471-12486/com.example.CardboardUnityDemo D/Unity﹕ Created framebuffer: resolution[1280x720], rgba[8/8/8/8], depth+stencil[24/8], samples[0]
05-29 16:44:03.987  12471-12559/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/System.Core.dll (this message is harmless)
05-29 16:44:04.047  12471-12559/com.example.CardboardUnityDemo D/Unity﹕ Platform assembly: /data/app/com.example.CardboardUnityDemo-2.apk/assets/bin/Data/Managed/System.dll (this message is harmless)
05-29 16:44:04.588  12471-12486/com.example.CardboardUnityDemo A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 12486 (UnityMain)

**Comment by nathanmartz** [comment]
Closing old issues. Likely fixed in new versions of Unity and SDK.
