### ISSUE TITLE
Luminosity

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#35]
It seems that SDK 0.5 is pushing screen luminosity to the maximum which is, I find, a bit exaggerated: whites are blinding and dark tones are bleeding...
Will you fix it (from my experience 50% lum is the best) or give control over it or leave it as is (and I'll rework my lightmaps)?
My preference would be having control. Door scenes may require blinding whites. 

Thanks!﻿

**Comment by MiCkSoftware** [comment]
-Door +Some

**Comment by smdol** [comment]
This seems like a good idea, although the results could vary across phone models.  Maybe the brightness level should be a user control (through the settings button), and all the SDK needs to do it make sure it is constant.

**Comment by MiCkSoftware** [comment]
Each way had drawbacks and benefits. I'll vote with your choice. Could you just confirm that next release will not push brightness to max? Do that I don't rebuild my lightmaps for nothing 😀. It's really a pain to tune!😂

**Comment by MiCkSoftware** [comment]
-vote +cope 😴

**Comment by smdol** [comment]
Not setting brightness to max is easy to do.  In the short term, it can be a developer setting.  That ought to be deliverable in the very near future.  (Notice I am not actually committing -- not allowed to.)

**Comment by MiCkSoftware** [comment]
Thanks for the feedback. That's kind. I'll wait for a few days and see if something pops out before reworking lightmaps in Alien Apartment (my app).
PS: I posted also on G+ about this "issue": https://plus.google.com/108926424989499203010/posts/dbcqzp8MTZA

Cheers!
MiCk.

**Comment by MiCkSoftware** [comment]
I had a look into the activity class (for the other issue) and saw brightness is set to 55f... Don't you meant .55f?

Cheers.
MiCk.

**Comment by smdol** [comment]
Interesting.  It is set to 1.0f in code.

**Comment by MiCkSoftware** [comment]
Interesting. After tons of unity bugs now we have bugs in eclipse decompiler...

**Comment by MiCkSoftware** [comment]
...Or not.. 

 private void startImmersiveMode();
[...]
    10  putfield android.view.WindowManager$LayoutParams.screenBrightness : float [55]

Sorry it seems I'm a pretty bad disassembled bytecode reader :(
(misinterpreted 55 as a value instead of a pointer).
Anyway, I'm still interested in having this value being adjustable from Mono in the SDK.

Thanks for your support.
Cheers.
MiCk.

**Comment by omgware** [comment]
Is there any ETA on a possible hotfix that would let devs choose not to force brightness? 
It doesn't seem to be much important, but in fact it is because it wouldn't be any clever to release a game on android where 100% brightness is always forced (plus fixed 60fps for any sane cardboard app), as it will drain battery so fast that almost every user will complain.
Is there anything we can do on our end right now other than reverting to v0.4.10?

**Comment by smdol** [comment]
Sorry for the delay in response.  Things got pushed back.  Adjustable brightness is still TBD.

**Comment by MiCkSoftware** [comment]
The more I think of it the more I see it as a killer function. I can imagine pushing lightness when player is in exterior and droping it when entering somewhere. That would be great!

**Comment by LegACy99** [comment]
So, I sorta solved this by adding my own plugin which inherits GoogleUnityActivity and changed the brightness to follow user's setting on the onCreate() function. So far I don't see any problem with it.

@smdol could you foresee any problem from inheriting the activity? Well, other than the not-future-change-compatible of course.

**Comment by smdol** [comment]
That seems like it will work, aside from future compatibility.

**Comment by MiCkSoftware** [comment]
Hi @smdol!

Nothing around luminosity in 0.5.1?😕
Cheers.
MiCk.

**Comment by ReedL** [comment]
The release notes indicate that the luminosity change is out:
"The SDK no longer forces Android screen brightness to maximum, which was
introduced in v0.5."
https://developers.google.com/cardboard/unity/release-notes

**Comment by MiCkSoftware** [comment]
Omg @ReedL I've read carefully and still missed it. Going on vacations today. I need it! 😊

**Comment by MiCkSoftware** [comment]
@smdol closing this issue.

**Comment by ReedL** [comment]
Heh, NP, glad your issue got addressed! Enjoy your vacation!
