### ISSUE TITLE
UI Events not triggered (Unity 5 / SDK .5)

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#36]
Once this line has been called, unity UI events are (almost) not triggered anymore when loading a new scene without cardboard.SDK instanciated
activityListener = Create("com.google.vr.platform.unity.UnityVrActivityListener");
in
AndroidVRDevice.cs

**Comment by smdol** [comment]
Can you grab the output of "adb logcat"?  It will probably show some useful debug messages.

**Comment by MiCkSoftware** [comment]
Did it with -s Unity and nothing popped out. Even more stranger some buttons still trigger events if clicking repeatedly.
Any logcat filter suggestion? Unfiltered outpout is a flood...

**Comment by smdol** [comment]
Hmm.  Multiple scene projects were tested, and this wasn't seen, but maybe that was luck of the draw.  I can think of a mechanism that could cause this (double instantiation of the UnityVrActivityListener), which I can look into.  As a workaround, if you make the Cardboard object live across level loads, this should not occur.

**Comment by MiCkSoftware** [comment]
I confirm that if Cardboard is kept across level the issue does not occur. And when the problem is there, any call to Cardboard.SDK will solve it.
Also, I cross checked and dispose() is called at level end on java activity. Maybe some cleaning is missing. 
The other think I though about is the event queue possibly being popped twice and/or with some thread concurrency.

**Comment by smdol** [comment]
Fixed in the v0.5.1 release.
