### ISSUE TITLE
UI Blocking GazeInput

### ISSUE THREAD

**Issue by justinwasilenko** [googlesamples/cardboard-unity#37]
I have a HUD or UI in front of the MainCamera that is one texture covering the center of the screen, however using the GazeInput module, the GazePointer always moves right to the canvas, no matter the layer I have selected, Ignore raycasting, seperate UI layer, etc...

And a similar issue when I place non interactable ui elements on the screen, such as title text, I can't get the Gazepoint not to activate on those elements.

Using Unity 5.0.1 and sdk 5. Thx

**Comment by smdol** [comment]
Find the GraphicsRaycaster component, and try changing its mask to not hit the layer that holds those elements.

**Comment by justinwasilenko** [comment]
Been there tried that, no luck. Had the elements on the Ignore Raycast layer, as well as a separate layer. But independent of the layer, the UI always blocks the Raycast.
Maybe there is something else I am doing wrong, but layers don't seem to solve it.

**Comment by smdol** [comment]
Finally got a hint that might help:  Add a CanvasGroup to the UI object, and clear the "Blocks Raycasts" setting.

http://answers.unity3d.com/questions/830371/ui-46-image-blocks-mouse-click.htmlhttp://answers.unity3d.com/questions/830371/ui-46-image-blocks-mouse-click.html

**Comment by justinwasilenko** [comment]
I get a page not found on that link.

But what I did, because the UI element that is blocking the Raycast is none interactive, I deleted the Graphic Raycaster component  on that Canvas and now the cursor passes through to other objects. But I had no luck with using layers to select what to block and what not.

**Comment by smdol** [comment]
Oops, managed to paste the link twice before.  Try this:

http://answers.unity3d.com/questions/830371/ui-46-image-blocks-mouse-click.html

**Comment by smdol** [comment]
Summary of the answer at the above link:

Add a CanvasGroup component to the Canvas, and set its "Blocks Raycast" property to false.
