### ISSUE TITLE
iOS Let's get you set up & Black Screen

### ISSUE THREAD

**Issue by NewmanMDB** [googlesamples/cardboard-unity#39]
Hi, having issue with iOS Cardboard DemoScene
![88773cda4d0e9733795a72c78b52730f8f951c1fc72da076d7 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/7926520/8154585/53e1f1c2-1344-11e5-86c9-e9d3a86e81ba.jpg)

Unity 4.6.5
SDK: v0.5
Graphics API: GLES 2.0
Tried on different devices, and same result everywhere (Android works without any problem).

Already tried turning on/off Direct Render, and building development build.

Any ideas?

**Comment by NewmanMDB** [comment]
Commenting out launchOnboardingDialog() in CardboardAppController.mm -> solves that issue, but maybe there is another way?

void launchOnboardingDialog() {
/*
  CardboardAppController* app = (CardboardAppController *)GetAppController();
  [app startSettingsDialog:createOnboardingDialog(app)];
*/
}

**Comment by smdol** [comment]
This usually happens if you don't add resources.bundle to the Xcode project.  See https://developers.google.com/cardboard/unity/get-started-ios

**Comment by NewmanMDB** [comment]
Awesome, thanks!

**Comment by dill0wn** [comment]
Thanks!
