### ISSUE TITLE
Rendering Plugin 'Failed to get env' error when Native Distortion Correction is enabled

### ISSUE THREAD

**Issue by sh3rifme** [googlesamples/cardboard-unity#41]
With native distortion correction enabled, when running on a galaxy S5, i only see a black screen and logCat outputs hundreds of lines of 'In Native: could not get env' with the RenderingPlugin tag.

I'm running Unity 4.6.6f2 Pro with the v0.4.10 plugin. I only just noticed this issue, i had never previously used native distortion correction until now.

When i open a fresh project, and load the demo scene in, the distortion correction works as expected.

So clearly **I** have done something to stop it from functioning, but since I've been using this plugin for about 2 months in this app, i'm rather stumped as to what may be causing this. 

If anyone knows what might cause the rendering plugin to fail to get the environment, please do tell!

**Comment by MiCkSoftware** [comment]
Try to clean your plugin directory and import SDK again.

**Comment by sh3rifme** [comment]
Just tried it, no luck. Is it something to do with **when** the plugin is first called? Or does that not make a difference?

**Comment by sh3rifme** [comment]
How is the distortion correction simulated in the editor? Because that works fine, and i guess i could adapt that if push comes to shove.

**Comment by sh3rifme** [comment]
It seems an upgrade to v5.0 has fixed this issue.
