### ISSUE TITLE
Ios google cardboard setup crash. 

### ISSUE THREAD

**Issue by andrewnakas** [googlesamples/cardboard-unity#44]
I've had 2 reports from 15,000 installs that they can not get past the setup screen on their iOS devices with the cardboard app.

One was just a bad review, but the other tweeted and let me know that it he was on iOS 7.1.1 and and iPhone 5s. 

P.S
Outside of this problem, this is amazing. Thanks for uniting mobile VR.

**Comment by smdol** [comment]
Could you get a description of what was happening from the one who tweeted you?  Crash, black screen, no "Skip" button, ignored all screen touches, etc?

**Comment by nathanmartz** [comment]
Closing very old thread.
