### ISSUE TITLE
Unable to detect correct Input.touchCount with Cardboard SDK

### ISSUE THREAD

**Issue by jhclaura** [googlesamples/cardboard-unity#48]
Hi, I want to know if the device (Android phone) screen is been touched or not, so I used Input.touchCount. If Input.touchCount>0, then screen is touched. This works in a brand new project, but not after I imported the Cardboard SDK and used CardboardMain. 
When I activated CardboardMain GameObject, Input.touchCount = 0 when no finger touched, = 0 when one finger touched, = 1 when two finger touched, ... etc, which is not the correct finger number count, thus I can't tell if the screen is touched or not.
I guessed it's something to do with Cardboard.Triggered, but I couldn't find a way to change it in Cardboard.cs. Please advise or point the direction about what should I do, thanks!

**Comment by smdol** [comment]
This is a bug (or misfeature) of the v0.5 SDK.  It hides real screen touches (of the first finger) whenever Cardboard.SDK.VRModeEnabled == true, reporting them as Cardboard.Triggered instead.  It will be fixed in an upcoming release.

**Comment by jhclaura** [comment]
Thanks for the fast reply! Then do you know if there's other way to detect
if the touch is held? Thanks so much for the help!

Lauraaa from phone

**Comment by smdol** [comment]
When it is fixed, then Input.touchCount will work as you want it to.  In the meantime, you could use a previous version of the SDK (v0.4.9) which did not have this issue.  Make sure you Cardboard.SDK.TapIsTrigger = false too.

**Comment by jhclaura** [comment]
Got it I'll try the previous version. Thank!!

Lauraaa from phone
