### ISSUE TITLE
Settings Button and Alignment Marker have no effect, not shown in build

### ISSUE THREAD

**Issue by davidmarcbrown** [googlesamples/cardboard-unity#5]
Settings Button and Alignment Marker in `CardBoardMain` prefab are checked in the editor, but the settings button and alignment marker elements do not appear in build or preview.

Nexus 7, Unity 4.6

**Comment by smdol** [comment]
New release 0.4.9 is out.  It draws the alignment marker even if distortion correction is off, and also in the editor.
