### ISSUE TITLE
The picture through the lenses is split 

### ISSUE THREAD

**Issue by Angie-Ie** [googlesamples/cardboard-unity#53]
I am using phone device Xiaomi Mi Note (5.7") to run  cardboard demo for unity. Not sure if I'm doing something wrong but the image through the lenses is split and doesn't merge (overlapping image).
Try it in another 5.5" device and get the same result

**Comment by smdol** [comment]
Is it similar to the issue here?
https://www.reddit.com/r/GoogleCardboard/comments/3evtwk/stereo_cubemaps_viewer_in_unity/

Or like this one here?
https://plus.sandbox.google.com/106479673975069899471/posts/Dv7YPJUD8zJ

Let me know if either of those posts match, and if the ideas there help you.

**Comment by Angie-Ie** [comment]
i can't open https://www.reddit.com/r/GoogleCardboard/comments/3evtwk/stereo_cubemaps_viewer_in_unity/ .
I see picture in cardboard using xiomi note like this:
![stereoscopic-3d-rendering-best-practices1](https://cloud.githubusercontent.com/assets/8733724/8999360/40de19dc-3763-11e5-84da-51c302777810.jpg)
.

**Comment by ming-zhu** [comment]
Try adjusting the "Stereo Multiplier" value of the Stereo Controller to a lower value.

**Comment by nathanmartz** [comment]
Closing old thread. Please reopen if still relevant.
