### ISSUE TITLE
The underlying theory of Google Cardboard code

### ISSUE THREAD

**Issue by anhnguyenvn** [googlesamples/cardboard-unity#54]
Hello everyone,

I don't really know whether my question is posted in the right place. It's not an issue from this plugin. I will delete my question if someone lets me know it isn't right place to ask. I would like to know the theory behind Cardboard Unity implementation. I understand stereoscopic rendering but i couldn't map what i know to source code of Cardboard Unity. I did google search and couldn't find related information. The source code is commented so carefully however it is still so difficult for me to understand why and what source code is doing. If possible, would you please point me to some links or  resources that closely relate to this Cardboard Unity implementation? 

Thank you so much! I would appreciate any comments.

**Comment by MiCkSoftware** [comment]
Hi,

You may have more chance on g+ community.
It searching the web for stereoscopic rendering.
MiCk.

Le ven. 31 juil. 2015 11:34, Nguyen Hoang Anh <notifications@github.com> a
écrit :

**Comment by anhnguyenvn** [comment]
@MiCkSoftware Thank you. I will look for some advises in G+ community. I thought that the developers working on this SDK would better point me directly to resources they refer when implementing. Welcome any comments and I will close this issue in the next some days. Thank you.

**Comment by MiCkSoftware** [comment]
I didn't meant g+ in general but cardboard community held by Google people: https://plus.google.com/communities/111524380182206513071
