### ISSUE TITLE
0.5.1 in unity 5 no light rendering on floor with tiled material and compressed when using uvw repeated textures

### ISSUE THREAD

**Issue by POPSAUR** [googlesamples/cardboard-unity#58]
![screenshot_2015-08-07-13-11-47](https://cloud.githubusercontent.com/assets/13693087/9134712/29c96d42-3d07-11e5-9870-d4609bd443ae.png)
Samsung I9505 Galaxy S4

whats causing the compression?
any other suggestions for creating a tiled texture that receives light?

**Comment by smdol** [comment]
Does this also happen if you turn off VR Mode?

**Comment by POPSAUR** [comment]
no only in vr mode i get compression

**Comment by smdol** [comment]
Can you post a screenshot of it with VR Mode turned off, for comparison?

**Comment by POPSAUR** [comment]
![image](https://cloud.githubusercontent.com/assets/13693087/9145002/56a7d80e-3d51-11e5-8ff5-f8c9178346eb.png)

**Comment by smdol** [comment]
Wow, very interesting.  BTW, which version of Unity are you using?  I can try to reproduce it.

**Comment by POPSAUR** [comment]
cool its 5.0.2.f1

**Comment by POPSAUR** [comment]
the floor from the screenshots is 26 triangles with repeated uvw and material tiling 1,1, ive created a unity package with the floor https://drive.google.com/file/d/0B1Q-jiCG2F79Qi1hX0N5bndqR3c/view?usp=sharing

**Comment by smdol** [comment]
I tried your package in Unity 5.1.1, with the build platform set to Android.  Seems OK, but maybe I don't have all the same settings you did.  Here's a screenshot.  Did you see this in the editor or on the phone?

<img width="1456" alt="screen shot 2015-08-08 at 10 47 19 pm" src="https://cloud.githubusercontent.com/assets/10277940/9153725/961585b2-3e1f-11e5-99d3-2bbb54494a7f.png">

**Comment by POPSAUR** [comment]
yes no probs in editor or windows build but on my android Samsung I9505 Galaxy S4, tested on my samsung galaxy tab 2 now which has no compression, i will keep you updated

**Comment by POPSAUR** [comment]
no compression with unity 5.1.2 and reinstalled windows, so prob solved :D

**Comment by smdol** [comment]
OK, I'll close the issue.
