### ISSUE TITLE
FOV in preview different than FOV in build

### ISSUE THREAD

**Issue by davidmarcbrown** [googlesamples/cardboard-unity#6]
Using 16:10 preview and Unity Remote, I see this when I run DemoScene with the editor:

![This is correct FOV](http://i.imgur.com/XASiFEd.png)

This first image is correct, and looks fine on the device.

but after build and running on the device natively, it looks like this:

![This is incorrect FOV](http://i.imgur.com/I2ubsMS.png)

Device is 16:10 aspect ratio. These are both screenshots taken on the device.

This second image is incorrect, and produces double vision.

Nexus 7 2013, Unity4.6

**Comment by smdol** [comment]
Fixed in v0.4.5
