### ISSUE TITLE
Surface shader issue in stereo

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#60]
Unity 5.1.1f1
SDK 0.5.1

While using a surface shader to render fake reflections, half of objects faces are not rendered anymore (nor cubemap nor base texture)  in stereo rendering (direct render ON or OFF; everything is fine in basic 3D).
Same with Unity provided shaders (Legacy\Reflection\...)
![picture1](https://cloud.githubusercontent.com/assets/12721372/9247372/d6fd422c-41b2-11e5-9ec0-548e1c5254b5.png)

**Comment by smdol** [comment]
As a test, try this.  Clear the MainCamera's "enabled" checkbox, and turn on the "enabled" checkbox of the left and right eye cameras.  Does this make any difference to the problem?  (There may be other side effects too.)

**Comment by MiCkSoftware** [comment]
I'll try Monday.

Additional info:
- cubemap is displayed correctly on all faces. (It's not clear on my
screenshot)
- only tex2d is affected and is displayed at least partially and starts to
clamp at some point.
- when using blending in the shader everything is OK.... !

**Comment by MiCkSoftware** [comment]
Merge with [#61](https://github.com/googlesamples/cardboard-unity/issues/61)
