### ISSUE TITLE
Texture glitch in stereo render with bumped shader + directional lighmap

### ISSUE THREAD

**Issue by MiCkSoftware** [googlesamples/cardboard-unity#61]
Unity 5.1.1f1
SDK 0.5.1

Some textures on some faces part (not the whole face) are rendered with a glitch (like if they were partially clamped) in stereo rendering (direct render ON or OFF; rendered fine in basic 3D).
This seems to only happen in the following conditions:
* Mesh face is medium sized or big (several world units)
* Shader uses bump mapping
* Lighting baking is set to directional (and for sure object is light-mapped)

![picture2](https://cloud.githubusercontent.com/assets/12721372/9247669/69cbfb14-41b5-11e5-87d4-c571bc2923c0.png)

**Comment by smdol** [comment]
Does this happen when part of the face is off screen, or does that not matter?

**Comment by MiCkSoftware** [comment]
That does not matter but it seems to be clearly related to normals since I
can see moving artifacts as the player moves. On the other hand, normal
texture is displayed correctly and bumping is correct, only albedo is
affected/clamped. That' really weird.

Maybe the camera trick you suggested for the other issue I posted could
help here to. I'll test monday.

**Comment by MiCkSoftware** [comment]
Hi @smdol,

Made several tests including the one you suggested and it pointed down to native distortion correction.

Disabling it via debugDisableNativeDistortion solves this issue as well as issue (#60)[https://github.com/googlesamples/cardboard-unity/issues/60]

But this cannot work as a workaround because of FPS drop. 

Hope it will be fixed!

Cheers!
MiCk.

**Comment by smdol** [comment]
I have filed the bug internally, so it is being tracked.

**Comment by smdol** [comment]
BTW, what phone(s) did you see this on?

**Comment by MiCkSoftware** [comment]
Nexus 4 and Nexus 5 (which I just got back from broken screen repair...)

**Comment by smdol** [comment]
You may also want to report this to Unity.  They've fixed a number of bugs recently in the 5.x family that addressed issues that Cardboard apps have been running into.  These have to do with using the native rendering plugin interface + RenderTextures.  This problem feels like it *could* be one of those.

**Comment by MiCkSoftware** [comment]
It's still there in 5.1.3f1.
For the report why not but the native plugin is a bit of black box I'm not
sure I can report the issue correctly... Don't you have contacts with unity
teams?

**Comment by justinwasilenko** [comment]
I too have been getting these artifacts, same problem, large mesh from a distance. Up close they don't appear but from a distance they do.
Using the latest Unity 5.1 patch and the Standard shader with a normal map applied.
Posted a video to show the artifacts:
https://youtu.be/Sfflt8nqn_M

**Comment by D3m0n92** [comment]
Yeah! Same problem on some texture!

2015-09-12 11:21 GMT+02:00 Justin Wasilenko <notifications@github.com>:

**Comment by MiCkSoftware** [comment]
It seems surface shading is somehow affected by native distortion
correction. For now we have to choose between normals mapping and native
correction & fps.

**Comment by smdol** [comment]
The first thing worth trying is to switch from 16 bits to 24 bits for the depth map.  There are two places that 16 bits are used in the SDK:  CreateStereoScreen() in BaseVRDevice.cs and Render() in CardboardEye.cs (which is only used if you turn off Direct Render).

**Comment by MiCkSoftware** [comment]
I haven't tried changing depth map props yet. 
BTW, there may be a new piece to the puzzle: https://plus.google.com/115469489631889455889/posts/gpMZynVvhZB

**Comment by smdol** [comment]
Also, are you using any Image Effects or deferred rendering?

**Comment by MiCkSoftware** [comment]
Not at all.

**Comment by smdol** [comment]
Could you try the new v0.5.2 build and see if the Unity-based distortion avoids this problem?  Or if it doesn't.  (Either way, I'd like to know.)  BTW, on the Cardboard script, there's now a slider to downscale the RenderTexture.  You can get some extra FPS out of that perhaps.

**Comment by MiCkSoftware** [comment]
I confirm unity based correction does not distorts bump maps nor reflection
maps.

The resolution slider if a good tool. I was wondering what is the value
equivalent of 0.5.1 setting. Is it 1.0?

Cheers!

**Comment by smdol** [comment]
1.0 is basically equivalent to the old SDK, in that it does not change the default size of the RenderTexture.  This slider just multiplies the width and height of the default size, and makes the RenderTexture equal to that size instead.

**Comment by nathanmartz** [comment]
Closing old thread. Please reopen if issue persists using the 0.6.0 SDK.
