### ISSUE TITLE
Bundle contents of Plugins/Android as AAR

### ISSUE THREAD

**Issue by PrototypeNM1** [googlesamples/cardboard-unity#63]
As per comments in [this thread](http://forum.unity3d.com/threads/obsolete-providing-android-resources-in-assets-plugins-android-res-is-deprecated.315889/) Unity now supports nested Android Studio Projects and AARs in Plugins/Android. This would help reduce the clutter Cardboard currently adds to the Plugins/Android folder. This would also handle manifest merging allowing the Cardboard AndroidManfest.xml to be trimmed down.

**Comment by smdol** [comment]
That's a good idea.  Unity 4 will still be supported for the time being, so there would still be some clutter for that version since it doesn't support AARs.

**Comment by nathanmartz** [comment]
We're tracking this internally as a request for a future release. Closing.
