### ISSUE TITLE
Chromatic aberration compensation is absent

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#65]
It seems that Google Cardboard VR Unity SDK lacks chromatic aberration compensation, since the effect is quite noticeable.

Could you please implement a solution to compensate chromatic aberration effect in VR for Unity SDK ?

**Comment by smdol** [comment]
Which viewer are you using?  I don't see much chromatic aberration myself, but I understand it can be worse if the lens separation is very different from your actual eye separation.

The trouble with doing chromatic aberration correction on current mobile devices is that it absolutely kills the frame rate, which can then causes sickness and nausea instead.  So the problem would have to be pretty bad for a lot of people on a lot of devices to make the tradeoff worthwhile -- at least right now.

**Comment by MiCkSoftware** [comment]
These guys are doing it but I haven't checked by myself:
http://www.alpsvr.com

Cheers!
Mick.

**Comment by motorsep** [comment]
I am using this cardboard https://www.unofficialcardboard.com/ and I tried it with Galaxy S3, S5 and S6 Edge.

I figured that while Android hardware is quite fragmented, maybe it makes sense to have profiles (like you already do in Unity SDK) for most powerful devices (Galaxy S6 Edge and whatever phones come later this year and in 2016) with chromatic aberration correction as a togglable option ? (unless it would kill performance on any device)

**Comment by smdol** [comment]
I haven't tried ALPSVR either, but they are using the same kind of shader for distortion as the Cardboard SDK's fallback in-Unity shader, which @MiCkSoftware you have said in another bug is too slow for your app.  (That's without the additional texture lookups for aberration correction.)  Of course, the Cardboard rendering code could be a factor contributing to that performance, and it has room to be optimized.  So there's no reason to rule out adding CA as an option.  I'll log it internally as a feature request.

**Comment by MiCkSoftware** [comment]
Yes. It has to be slow I guess. Or maybe your shader is running into a
unity 5 issue.

**Comment by smdol** [comment]
There's a very nice viewer by GoggleTech, the C1-Glass, which has lenses whose separation can be adjusted.  They're pretty high quality too, and the viewer overall is as portable as any pair of glasses.  I really like it, and I don't notice any obvious aberration with them.  Might be worth trying to see if the aberration issue is related to eye-separation vs lens-separation.  (This is not to imply CA will never be addressed in the SDK, just something that can be done right away.)

**Comment by MiCkSoftware** [comment]
Afaik it depends more on the lenses size and profile/quality.

**Comment by smdol** [comment]
Yep, those are factors too.  Leaving aside quality of optics for a moment, basically, the chromatic aberration is minimized when your pupils are centered over the lenses and you are looking straight ahead.  Larger lenses make it easier to look farther off center, and of course the separation mismatch I mentioned previously also contributes.  Also, if your eyes are in certain prescription ranges or you have had laser surgery, then CA can be worse just from that.  Finally, as you said, quality of optics is a factor.

**Comment by Fredz66** [comment]
> The trouble with doing chromatic aberration correction on current mobile devices is that it absolutely kills the frame rate

The [Oculus Mobile SDK](https://developer.oculus.com/downloads/mobile/0.6.0.1/Oculus_Mobile_SDK/) and [CMOAR VR Cinema](https://play.google.com/store/apps/details?id=com.Cmoar.CmoarVirtualCinema) both support chromatic aberration correction.

**Comment by smdol** [comment]
Haven't looked at CMOAR yet, but Oculus Mobile is for Gear VR, which is running on a heavily modified Android stack.  The savings from those mods make the extra time for chromatic aberration worth it.  Stock Android isn't there yet (at least the last time we did performance testing for it).  I'm sure we'll reach that point before too long (I hope!).

**Comment by motorsep** [comment]
So when you plug S6 into Gear VR, another OS runs inside stock Android on S6 ? o.O

**Comment by smdol** [comment]
No, as I understand it, the Samsung version of Android has a bunch of "back doors" in it that Gear VR can use.  (It's not uncommon for phone manufacturers to modify Android in various ways for their hardware.)

**Comment by nathanmartz** [comment]
Closing old thread. Chromatic correction is unlikely to be part of the official Cardboard SDK due to GPU performance issues and the improving quality of cardboard lenses.
