### ISSUE TITLE
Location tracking ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#67]
As I was testing AA with the green/red cube scene yesterday, I noticed that if I squat down, the camera doesn't go down.

Is it possible to add position (vertical and on the ground plane) tracking to Unity SDK? If so, do you think you could provide a patch for testing and then release it in the next build of SDK ?

Thanks.

**Comment by mudream4869** [comment]
Hard. May need other sensor ...

**Comment by motorsep** [comment]
Well, there are accelerometer, gyro, proximity, compass and barometer on higher end phones. Plus GPS. So I wonder if any of those can be utilized to determine changes in vertical/horizontal positioning.

**Comment by smdol** [comment]
To do positional tracking for VR, you need accuracy within a few cm or less and latency in the 10s of milliseconds.  The existing phone sensors are definitely not good enough for that.  There's another Google project called Tango (https://www.google.com/atap/project-tango/) that is tackling that problem.  I've also seen attempts to do position tracking using the camera and a vision SDK like Qualcomm's Vuforia (https://developer.vuforia.com/).  That's still not quite in the "good enough" range, but is getting better.
