### ISSUE TITLE
Bluetooth gamepad controls in Unity SDK ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#68]
Does Unity SDK come with bluetooth gamepad controls by chance or is it something that can be added separately, through Asset Store for example?

**Comment by smdol** [comment]
You should be able to add those separately.  They appear through the Input class as buttons and axes.

**Comment by bamboofx** [comment]
try https://github.com/speps/XInputDotNet/tree/master/XInputUnity.
