### ISSUE TITLE
Android. TapIsTrigger=false cause Keycode.Escape event firing on device rotation

### ISSUE THREAD

**Issue by ITurchenko** [googlesamples/cardboard-unity#69]
When I set TapIsTrigger=false in Cardboard script on scene, I got passing
```java
 if (Input.GetKey(KeyCode.Escape)) {
    Debug.Log("Escape was pressed");
 }
```
if device was abruptly rotated on 90 (or more) degree.

It causing some problems in my project because I want to handle device back button pressing in addition with screen tapping and Cardboard magnet triggering separately.

**Comment by smdol** [comment]
The 90 degree rotation causes an event called "Tilt".  When TapIsTrigger is turned off, then tilt appears as an Escape key (just like magnet triggers appear as screen taps).  You can stop this in your current project by editing CardboardAndroidDevice.cs in Assets/Cardboard/Scripts/VRDevices, and removing the "injectKeyPress" line in ProcessEvents().

**Comment by ITurchenko** [comment]
Thanks a lot!

**Comment by smdol** [comment]
This is changed in v0.5.2, which now has a separate "Back Button" in the top left corner of the screen.  This button is equivalent to the normal Android back button, which is usually hidden in VR mode.  The Tilt event still exists but has no key equivalent anymore.
