### ISSUE TITLE
"go back" button (to the right from Home button) does nothing

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#71]
When running an app made with Unity for Cardboard VR, "go back" button (to the right from Home button) works as expected. However, when running a default SDK scene built and deployed with Unity, pressing "go back" button does nothing. So the only way to get out of the app is by pressing Home button.

**Comment by smdol** [comment]
Unity sees the Back button as an Escape keypress, so you can respond to it using Input.GetKeyUp().
