### ISSUE TITLE
Textures stop copying with distortion enabled on SOME android devices

### ISSUE THREAD

**Issue by SoylentGraham** [googlesamples/cardboard-unity#72]
Apologies for the vague title, but making a note of this before I forget.
I have a unity plugin which writes to textures (texture2d and rendertextures) every frame. (Pixel uploads and FBO writes)
My opengl work is done via a normal gl.IssuePLuginEvent callback (which is being called)

With distortion enabled these textures stop getting written to (no errors from opengl on my end, nor anywhere else), I get the first frame, but that's all.
I can toggle the stereo effect fine, but distortion breaks it. 
Enabling multithreaded rendering (a known issue) doesn't render my geometry at all, so I'm not sure if that affects it.

Samsung Note4's seem to be fine, Sony Z1 compact has this issue.

I have not replicated this issue with any other plugins or GL state settings.

Is there [unobfuscated] source, or can someone tell me what the EnableDistortion does in regards to the opengl state? 

Using opengl ES 3.

**Comment by smdol** [comment]
The Cardboard SDK also uses GL.IssuePluginEvent() to jump into native code for distortion correction, so it looks like both your plugin and the Cardboard SDK are supplying a native UnityRenderEvent() function.  In that case, I'm not sure which one Unity will call from GL.IssuePluginEvent (first native library loaded wins?), and I'm actually surprised it works on any phone.

If you are certain your native function is being called by GL.IssuePluginEvent(), then you can get the SDK to handle distortion entirely in Unity as follows.  Edit **BaseCardboardDevice.cs** in *Assets/Cardboard/Scripts/VRDevices*, and make the following changes:

- Set *debugDisableNativeDistortionCorrection* = **true**
- Set *debugDisableNativeUILayer* = **true**
- In *PostRender()*, remove or comment out the entire **if (vrMode) { ... }** block

**Comment by SoylentGraham** [comment]
It calls the function for all libraries (I worked at unity, I know how it
works internally, it's easy for external libs, much more awkward on static
linked iOS projects  :)
I have a unique id and ignore other plugins' plugin events. (If the
cardboard sdk doesn't have a unique IssuePluginEvent id I'd highly
recommend one)
IIRC the first loaded lib is called first, but that order, I can't
remember. The important thing is that they ARE all called.

I'll try this in the morning... Can you elaborate at all on what the Google
lib does when distortion is enabled? I assume it must change a state I
don't handle. PluginEvent work is still synchronous on the render thread
(in the cardboard sdk case this obviously has to be on the main thread), so
something must be change in the state that possibly I can revert?


On Thursday, August 27, 2015, smdol <notifications@github.com> wrote:

> The Cardboard SDK also uses GL.IssuePluginEvent() to jump into native code
> for distortion correction, so it looks like both your plugin and the
> Cardboard SDK are supplying a native UnityRenderEvent() function. In that
> case, I'm not sure which one Unity will call from GL.IssuePluginEvent
> (first native library loaded wins?), and I'm actually surprised it works on
> any phone.
>
> If you are certain your native function is being called by
> GL.IssuePluginEvent(), then you can get the SDK to handle distortion
> entirely in Unity as follows. Edit *BaseCardboardDevice.cs* in
> *Assets/Cardboard/Scripts/VRDevices*, and make the following changes:
>
>    - Set *debugDisableNativeDistortionCorrection* = *true*
>    - Set *debugDisableNativeUILayer* = *true*
>    - In *PostRender()*, remove or comment out the entire *if (vrMode) {
>    ... }* block
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/cardboard-unity/issues/72#issuecomment-135574045>
> .
>


-- 

- Graham Reeves
- http://www.grahamreeves.com/

**Comment by smdol** [comment]
Ah, I was beginning to suspect from your post that Unity might be calling *all* the UnityRenderEvent functions.  Definitely will take your suggestion for using a unique id.

Anyway, the Cardboard native distortion code is given the GL texture id of the RenderTexture that was used to render the scene.  It just renders a mesh with a shader sampling that texture with a barrel distortion applied to the coordinates, once for each eye.  It also draws the vertical line between the eyes.  The code does try to save and restore GL state while doing this, but I don't personally know how extensive that is.

**Comment by SoylentGraham** [comment]
Oh it does call all the render event functions, (in this case, 3 are called)

You say one for each eye... But there are two seperate camera.renders
(which stall the main thread but that's a seperate problem)
Are the distortion meshes rendered once per IssuePluginEvent ?

I'm thinking out loud now, but does it change the... glActiveTexture?
That's something I don't explicitly set

Is there any chance I can see the code inside the compiled libs?

On Thursday, August 27, 2015, smdol <notifications@github.com> wrote:

> Ah, I was beginning to suspect from your post that Unity might be calling
> *all* the UnityRenderEvent functions. Definitely will take your
> suggestion for using a unique id.
>
> Anyway, the Cardboard native distortion code is given the GL texture id of
> the RenderTexture that was used to render the scene. It just renders a mesh
> with a shader sampling that texture with a barrel distortion applied to the
> coordinates, once for each eye. It also draws the vertical line between the
> eyes. The code does try to save and restore GL state while doing this, but
> I don't personally know how extensive that is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/cardboard-unity/issues/72#issuecomment-135576574>
> .
>


-- 

- Graham Reeves
- http://www.grahamreeves.com/

**Comment by smdol** [comment]
(Definitely like to follow up with you about that main thread being stalled...)

The two eye cameras are rendered into a single RenderTexture, side by side.  That texture's id has been passed to the native code during an init phase.  There's only one GL.IssuePluginEvent() call per frame in the SDK, and the native code it jumps into renders the distortion mesh twice, once for each eye, to the screen.  I don't think it changes glActiveTexture but I'm not absolutely certain.

As for seeing the code, it hasn't been open sourced.  If/when that happens (hopefully "when" where "when" == "soon", but that's just my personal feeling)...

**Comment by SoylentGraham** [comment]
Even a list of gl calls would be handy (I've not figured out how to get
that from android yet... But a generic tool recommendation would be very
well received)

I'm drunk and off to bed now, will try a few things in the morning.

feel free to mail me about the main thread stall, but mosu it's just that
camera.render stalls the main thread until the render thread is done(gl
thread acquire/sync in the unity code): I've tried loads of things
(delegates deffered until the render thread, putting cardboard scripts last
in the processing list) to get around it, but I think it's just not been
thought about in the unity pipeline.
And REALLY only applies to multithreaded rendering anyway.

My work around was to make the split-view render something not based around
camera.render, but as soon as you start fiddling with the culling you're
just emulating unity's native VR work.
Off topic now, I'll reply to this thread if I find any thing.


On Friday, August 28, 2015, smdol <notifications@github.com> wrote:

> (Definitely like to follow up with you about that main thread being
> stalled...)
>
> The two eye cameras are rendered into a single RenderTexture, side by
> side. That texture's id has been passed to the native code during an init
> phase. There's only one GL.IssuePluginEvent() call per frame in the SDK,
> and the native code it jumps into renders the distortion mesh twice, once
> for each eye, to the screen. I don't think it changes glActiveTexture but
> I'm not absolutely certain.
>
> As for seeing the code, it hasn't been open sourced. If/when that happens
> (hopefully "when" where "when" == "soon", but that's just my personal
> feeling)...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/cardboard-unity/issues/72#issuecomment-135579961>
> .
>


-- 

- Graham Reeves
- http://www.grahamreeves.com/

**Comment by smdol** [comment]
I read a great suggestion on a blog post somewhere:  if you run on a Tegra-based Android device, you can use PerfHud to grab all the gl calls.

On iOS, you can do this right in Xcode.  The Unity gl pipeline might be different on iOS (make sure it doesn't use Metal), but the Cardboard SDK gl calls should be the same as on Android.

**Comment by SoylentGraham** [comment]
Ah, that's good to know!
I doubt it needs any specific extensions too. I'll do that.
Just to reiterate for any readers, doesn't happen on every android device,
so just another quirk to work around. (Nothing's changed in 17 years ;)

On Friday, August 28, 2015, smdol <notifications@github.com> wrote:

> I read a great suggestion on a blog post somewhere: if you run on a
> Tegra-based Android device, you can use PerfHud to grab all the gl calls.
>
> On iOS, you can do this right in Xcode. The Unity gl pipeline might be
> different on iOS (make sure it doesn't use Metal), but the Cardboard SDK gl
> calls should be the same as on Android.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googlesamples/cardboard-unity/issues/72#issuecomment-135583691>
> .
>


-- 

- Graham Reeves
- http://www.grahamreeves.com/

**Comment by smdol** [comment]
It looks like glActiveTexture *is* being set, but the code saves and restores it.

**Comment by smdol** [comment]
@SoylentGraham Question:  Does Graphics.DrawMeshNow() cause any performance hiccups if used in an OnPostRender() method?

**Comment by nathanmartz** [comment]
This issue has been fixed with the native Unity distortion pass.
