### ISSUE TITLE
iPhone 5s, 6, 6 plus: not working

### ISSUE THREAD

**Issue by smxthereisonlyone** [googlesamples/cardboard-unity#74]
Warnings:

Built-in UI layer disabled. Causes: [Requires OpenGL] UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()

Built-in distortion correction disabled. Causes: [Requires OpenGL] UnityEngine.EventSystems.TouchInputModule:ProcessTouchEvents()

**Comment by smdol** [comment]
That indicates Unity is using Metal for the graphics API instead of OpenGL.  You can control this in the Player Settings panel.  But the app should still work either way -- these are warnings, not errors.  Are you not getting distortion correction or the alignment marker?

**Comment by smxthereisonlyone** [comment]
@smdol  I am not getting the alignment marker. What do I have to change in the player settings?

**Comment by smdol** [comment]
In Unity 4, under Configuration in "Other Settings", change "Graphics API" from to "Force OpenGL ES 2" (or ES 3).

In Unity 5, under Rendering in "Other Settings", uncheck "Automatic Graphics API" and then remove Metal from the list of APIs that appears.

**Comment by smxthereisonlyone** [comment]
@smdol I did just that and it still doesn't work

**Comment by smdol** [comment]
OK, first, did the warnings you listed in the first post go away?  Next, make sure you have the Alignment Marker checkbox enabled in the Cardboard component (on CardboardMain's root game object).  At this point, is the Alignment Marker all that is missing?

**Comment by smxthereisonlyone** [comment]
@smdol I didn't see whether the warnings go away but the Alignment Marker box was checked. But still, screen all black. The only thing I could see was the gear icon.

**Comment by smdol** [comment]
Ah, screen all black is a different problem altogether.  It wasn't clear from your first post that you were seeing nothing at all.  OK, let's tackle that.  First, reenable Metal.  Then go in to the Cardboard options and disable VR Mode Enabled, so none of the stereo rendering stuff is active.  It is still black?

**Comment by smxthereisonlyone** [comment]
If I do that I see something but it's the screen is changing rapidly and switiching between render textures, also sometimes shortly black.

**Comment by smdol** [comment]
What's your version of Unity?

**Comment by smdol** [comment]
New v0.5.2 release should show the UI layer regardless of Metal or OpenGL, since it's now implemented using normal iOS View and ViewController objects.

**Comment by svetlanama** [comment]
In Unity 5, under Rendering in "Other Settings", uncheck "Automatic Graphics API" and then remove Metal from the list of APIs that appears.

Thanks, it works!
