### ISSUE TITLE
Cardboard Community ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#75]
Sorry to post here, since it's not an issue related to programming / content per se.

I can't find an active online community for Unity-based Google Cardboard VR :/ Do you know of any? (I am looking for a programmer to modify Cardboard Unity SDK scene a bit)

Thanks.

**Comment by smdol** [comment]
Two communities that are about Google Cardboard are here:

Reddit: https://www.reddit.com/r/googlecardboard
Google+:  https://plus.sandbox.google.com/u/0/communities/111524380182206513071

They aren't Unity-based per se, but anyone talking about development is quite often referring to Unity.
