### ISSUE TITLE
crash on iOS when scanning cardboard QR code on 0.5.1

### ISSUE THREAD

**Issue by Scott-Driscoll** [googlesamples/cardboard-unity#76]
I get the following error when scanning a cardboard QR code with a Unity (4.6.4) project running 0.5.1 cardboard after hitting the gear settings button:

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 1 from section 0 which only contains 1 rows before the update'

I don't get this on 0.5.0. Also, there aren't any problems with the initial onboarding scan.

http://stackoverflow.com/questions/32406983/nsinternalinconsistencyexception-error-crash-when-scanning-cardboard-qr-profil/32407174#32407174

**Comment by smdol** [comment]
Just to check:
-  You have the iCloud capability enabled in the Xcode project?
-  You have "Sync with Cardboard" enabled in the CardboardMain settings?

**Comment by nathanmartz** [comment]
Closing old thread.
