### ISSUE TITLE
ToggleVRMode

### ISSUE THREAD

**Issue by justinwasilenko** [googlesamples/cardboard-unity#77]
I have tried the demo scene, and the button that calls the function ToggleVRMode works fine,
When I import the same button into my scene, or create my own button that calls this script:

  public void ToggleVRMode() {
    Cardboard.SDK.VRModeEnabled = !Cardboard.SDK.VRModeEnabled;
  }

The it will toggle VR Mode. However the problem I am having is, the next 'click' or 'Fire' event causes the VRMode to revert back to VRModeEnabled being true. It doesn't matter where I click. So I can never turn off VRMode like intended. Like the button is being pushed twice without actually pushing the button twice.

**Comment by smdol** [comment]
How are you highlighting the button?  Are you using GazeInputModule, or something else?

**Comment by justinwasilenko** [comment]
With GazeInputModule

**Comment by lesmo** [comment]
Perhaps TapIsTrigger is conflicting? Are you sure GazeInputModule is before
the Touch Input component?

You could also make your method check if has been run before in certain
time period (maybe a second) and only trigger if it hasn't during that
time, so effectively it'll just run once.

**Comment by justinwasilenko** [comment]
Yes GazeInput is above the TouchInput, and just tried it with TapisTrigger turned off and it gave me the same result.
I just tried to recreate it with a new empty scene and could not, it works like it should. So something I have done I guess causes the problem but not sure what could effect the button like that. Even creating a new button and I get the same result.

**Comment by lesmo** [comment]
Uhm... maybe you have two instances of GazeInputModule (perhaps
accidentally dragged the component to another Game Object)? You're gonna
have to re-create your steps to get to a point where you can see what is
going on.

Perhaps more details about your setup? I mean, if it can't be reproduced
many of us can't really help much. 😟

**Comment by justinwasilenko** [comment]
I checked the scene, everything is how it should be. On the plus side this only happens in the editor, not happening in the build of my game.
Might have to rebuild that scene anyways, because I get crazy black artifacts when built for Android and not in the editor on some objects. Not sure what is going on there. But again its only in the one scene.
