### ISSUE TITLE
How to utilize vibration ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#78]
Is there a way to utilize phone's vibration using Unity SDK ?

For example, when tapping the cube, I'd like phone to vibrate for specified duration and with specified power.

Alternatively, vibrate when cube "teleports" to another location.

Thanks!

**Comment by smdol** [comment]
The only way I know offhand is Handheld.Vibrate:

http://docs.unity3d.com/ScriptReference/Handheld.Vibrate.html

**Comment by steveulrich** [comment]
Handheld.Vibrate() does not allow you any configuration, unfortunately. I believe it is just a flat "power" for a 1 second duration.

**Comment by motorsep** [comment]
I found a couple of things on Asset Store:

https://www.assetstore.unity3d.com/en/#!/content/10982
https://www.assetstore.unity3d.com/en/#!/content/7405
