### ISSUE TITLE
BaseAndroidDevice.cs: error CS1674: `AndroidJavaClass': type used in a using statement must be implicitly convertible to `System.IDisposable'

### ISSUE THREAD

**Issue by D3m0n92** [googlesamples/cardboard-unity#80]
I have this error on script: BaseAndroidDevice.

Unity 5.1.3p2

**Comment by smdol** [comment]
AndroidJavaClass used to be an IDisposable... I wonder if that change in the recent versions of Unity?  I'll check.  There are a couple of places in that script where it is used like this:

    using (AndroidJavaClass player = new AndroidJavaClass("com.unity3d.player.UnityPlayer")) {
        androidActivity = player.GetStatic<AndroidJavaObject>("currentActivity");
    }

Try changing it to just this:

    AndroidJavaClass player = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
    androidActivity = player.GetStatic<AndroidJavaObject>("currentActivity");

Does that fix the error?  If so, you can do that and carry on.  Also, I'll install 5.1.3 (I have 5.1.1) and check it out too.

**Comment by D3m0n92** [comment]
Now i update Unity to 5.2.0f3. I'll check!

**Comment by D3m0n92** [comment]
Yes, 

"AndroidJavaClass player = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
androidActivity = player.GetStatic<AndroidJavaObject>("currentActivity");"

Fix the problem.. But now i have this line on error: (same using)

      using (AndroidJavaClass player = new AndroidJavaClass(cardboardClass)) {
        androidActivity = player.CallStatic<AndroidJavaObject>("getActivity");

**Comment by smdol** [comment]
Make a similar change:

AndroidJavaClass player = new AndroidJavaClass(cardboardClass);
androidActivity = player.CallStatic<AndroidJavaObject>("getActivity");

There may be a couple more "using (...) { ... }" in the SDK.  Make the same kind of change for each.
