### ISSUE TITLE
Unity 5.2 is out - Cardboard SDK update ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#81]
Is there an updated SDK coming for Unity 5.2.x soon ?

http://unity3d.com/unity/whats-new/unity-5.2

**Comment by lesmo** [comment]
... I haven't updated to 5.2, but we haven't had issues with it on 5.1.
Have you found any problems you'd think you'd like to share?

**Comment by D3m0n92** [comment]
I use 5.2.0. Zero problem for now..

**Comment by motorsep** [comment]
@lesmo I haven't updated yet, but multithreaded renderer wasn't working with Cardboard VR in 5.1, AA wasn't working (and most likely still won't) either.

**Comment by motorsep** [comment]
@D3m0n92 Does multithreaded renderer work for you in VR ?

**Comment by omgwtfgames** [comment]
@motorsep I just tested it with Unity 5.2.0f3 and the Cardboard SDK for Unity 0.5.1 - it now works ! Some quick profiling suggests turning it on it improves performance too.

**Comment by motorsep** [comment]
@omgwtfgames Sweet! Thanks for sharing this info!

**Comment by D3m0n92** [comment]
With vuforia sdk not working.. video player is Black.
Il 11/Set/2015 16:25, "motorsep" <notifications@github.com> ha scritto:

**Comment by motorsep** [comment]
@D3m0n92 I don't use Vuforia and I don't think I ever will - it's prohibitively expensive.

**Comment by D3m0n92** [comment]
Yeah, but now this is the realy innovation on mobile with cardboard sdk
Il 11/Set/2015 19:35, "motorsep" <notifications@github.com> ha scritto:

**Comment by justinwasilenko** [comment]
I updated to 5.2 and here are the Warning messages that pop up. Other than that it's running good.

Assets/Cardboard/Scripts/VRDevices/BaseCardboardDevice.cs(120,10): warning CS0618: `UnityEngine.GL.IssuePluginEvent(int)' is obsolete: `IssuePluginEvent(eventID) is deprecated. Use IssuePluginEvent(callback, eventID) instead.'

Assets/Cardboard/Scripts/VRDevices/BaseCardboardDevice.cs(96,54): warning CS0618: `UnityEngine.Texture.GetNativeTextureID()' is obsolete: `Use GetNativeTexturePtr instead.'

Plus 3 more from the Legacy scripts.

Multi-threading works when enabled now, except if you switch windows and come back you are greeted with the normal black screen from multi threading before.

**Comment by smdol** [comment]
OK, thanks!  I think I have an idea on that black screen from returning to the app.  Can you try this?

In Cardboard.cs, in the StereoScreen property, there is this line in the set {} block:

      if (stereoScreen != null && !stereoScreen.IsCreated()) {
          stereoScreen.Create();
      }

The idea is to move these lines into the get {} block, right before the line "return stereoScreen;".

**Comment by justinwasilenko** [comment]
Just gave it a try, whole screen is black now without alt tabbing. I get the settings button in the middle but the 'eyes' are black.

**Comment by 2600th** [comment]
Yup tried the same using Unity 5.2 and current sdk and found that disabling distortion correction causes no black screen with multithreading enabled on returning to application.

**Comment by smdol** [comment]
@justinwasilenko OK, so I guess that suggestion isn't the right fix.

@2600th you comment does strengthen the suspicion that something has gotten messed up or reset in the StereoScreen on returning to the app, because when distortion correction is off, this texture is not used:  the scene is rendered directly to the display.  

Well, we'll keep working on this...

**Comment by rtauziac** [comment]
I had some serious issues with the SDK. I have a project created with Unity 5.1.2, and now after upgrading it to 5.2, the eyes are divergent, making impossible to focus on far objects. I tried with an empty projects, not better.

I downgraded my Unity back to 5.1.3 and created a new project, SDK is functional again.

**Comment by smdol** [comment]
@rtauziac What phone do you use?  Is there a way you can print out the Screen.dpi value that Unity returns in both 5.1.2 and 5.2?  This number is passed to the native layer of the SDK, where it is used to calculate the physical size of the screen (in mm).  Different values would cause the SDK to think the phone size changed, which would directly cause the effect you describe.

**Comment by rtauziac** [comment]
With unity 5.2.1, it measures 560 dpi, with 5.1.3 it tells me 493,438.

I'm using a Nexus 6 with a KnoxV2 cardboard

**Comment by andiwinata** [comment]
I have the same problem also, in Unity 5.1.2 when I set it to Nexus 5 size, it only consumes like 3/4 size of the screen. But in 5.2.1 it consumes the whole screen and causes wrong left and right eye view

**Comment by smdol** [comment]
If you go into the function Init() in BaseCardboardDevice.cs and use Screen.xdpi, Screen.ydpi instead of Screen.dpi, do you get any different results?

**Comment by andiwinata** [comment]
Hi, how do you get the Screen.xdpi and Screen.ydpi? it doesn't have those fields

**Comment by smdol** [comment]
Hm.  So it doesn't.  It used to, but I guess they got retired.

**Comment by smdol** [comment]
Actually, I may be imagining things -- those fields are available on Android DisplayMetrics.

**Comment by andiwinata** [comment]
So any way to do it in unity?

**Comment by smdol** [comment]
So it looks like Unity 5.2 is doing something unexpected, or undocumented.  It's probably worth asking them why the DPI changes so much in 5.2 -- is it a bug or a fix?

**Comment by smdol** [comment]
I found some code on the Unity Forums that lets you ask Android directly for the info:
    http://forum.unity3d.com/threads/finding-physical-screen-size.203017/#post-1373867
You can get both width and height, plus xdpi and ydpi.

It may be worth trying this code in 5.2, to see if it matches more closely what you see with Unity 5.1.  If you do, let me know whether it works out.

**Comment by smdol** [comment]
I just noticed that the code I linked above is calling "getMetrics".  You might want to try "getRealMetrics" instead.

**Comment by andiwinata** [comment]
I followed your instructions and it seems now working. The screen size is back to normal now and left and right eyes are correct now

**Comment by Tojuro** [comment]
I was seeing the same thing after the update to Unity 5.2 (left & right eyes reversed), and the code above appeared to fix it, at first.    Now the eyes are not reversed anymore, but everything in view is mirrored.    So, I'm playing video in a sphere, and all the text you can see is backwards.

**Comment by andiwinata** [comment]
are you sure it is not your video plugin? because in case of mine, i need to put sphere mirror for the UV  that playing video to get it right. How about static image? it seems not reversed in mine

**Comment by andiwinata** [comment]
Also how about iOS screen.dpi?

**Comment by smdol** [comment]
iOS is much simpler.  There are basically 2 possible DPI values, the one for 6 Plus (and now 6 Plus S, I think), and everything else.  One of the benefits of having a single hardware vendor (Apple), I suppose.

**Comment by andiwinata** [comment]
I mean how to get the dpi of ios since it is AndroidJavaObject

**Comment by gautamjain** [comment]
I've been having the same issue as @rtauziac - with regards to incorrect size and distortion.  I noticed this on Unity 5.2.1 and 5.1.4.  After downgrading again to 5.1.3, everything worked as expected.  

Here are the screen DPI numbers I was getting back:

| Unity Version | Screen.DPI - Nexus 6 | Screen.DPI - Moto X (2014) |
|:-------------:|:--------------------:|:--------------------------:|
| 5.2.1 | 560 | 480 |
| 5.1.4f1 | 560 | 480 |
| 5.1.3f1 | 493.438 | 423.0495 |

**Comment by smdol** [comment]
The new release of the SDK (v0.5.2) should fix these DPI issues for both Android and iOS.
