### ISSUE TITLE
Time Warp from 0.5.5 SDK into Unity SDK ?!

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#84]
So I just saw this https://www.reddit.com/r/GoogleCardboard/comments/3efkj6/cardboard_native_sdk_055_adds_electronic_display/ and I am so hopeful that it will make its way into Unity SDK :)

Can you please tell us when "electronic display stabilization" makes it into Unity SDK ?

EDIT: Wow, Android SDK for a lot of goodies from 0.5.1 to 0.5.6. Can't wait for all that to trickle down to Unity SDK ! :)

**Comment by ReedL** [comment]
If/when that functionality is implemented, I'm sure it will be mentioned in the release notes. I briefly considered submitting an enhancement request for it, but I'm pretry certain it is already planned.

**Comment by motorsep** [comment]
That's understandable. I am wondering about when, if ever, it will happen (there gotta be some approximate time frame set by developers themselves for implementing things to Unity SDK)

**Comment by ReedL** [comment]
Just based on #35 my guess is that they can't comment on upcoming features or even potential upcoming features unfortunately.

**Comment by smdol** [comment]
@ReedL That is correct.  Sorry.  But it will be announced in the release notes when a requested feature is added, and I typically come back through these issue pages and post a note here too.

**Comment by motorsep** [comment]
I see an updated Unity SDK was propped into the repo recently - looking really good so far ! :+1: 

Is there a chance that timewarp made it into this build? (I don't see anything about in the release notes, but I figured it doesn't hurt to ask :) )

**Comment by smdol** [comment]
Yes, it is actually in there, although I don't think it works as well as hoped.  You can enable it in code:

    Cardboard.SDK.ElectronicDisplayStabilization = true;

Also, you need to set the distortion method to "Native" because the Unity method doesn't support it.

As for why I'm down on it, I think it increases the jitter you see rather than decreasing it *whenever you hold the Cardboard in your hand*.  If you use a headstrap, it may work better (but I haven't tried).

**Comment by motorsep** [comment]
Hmm.. What would I lose by going with native distortion ?

**Comment by smdol** [comment]
That's what you used to be using in the prior release, so there won't be any change relative to that.  The new Unity distortion method should help performance a bit, plus you can use Metal on iOS.

**Comment by andregm3** [comment]
i got a lot more fps by just disabling distortion correction:
![distunity](https://cloud.githubusercontent.com/assets/4154732/12909148/2541f44a-cee5-11e5-9766-9fd6a17f99c7.png)
