### ISSUE TITLE
Framerate goes down on Samsung Galaxy S6 / gpu cpu throttling problem

### ISSUE THREAD

**Issue by noemis84** [googlesamples/cardboard-unity#85]
We have several cardboards untily last week, all set up as default viewer, cause they have no qr code. No we got a new one from zaak, a cardboard v2. We used the settings button in app, scanned the code and... the framerate went down. VERY strange. I have always a frameratecounter located in 3D Space and always have 50 - 60 frames, which is ok... after switching viewer nearly constant 25. Not enough, and it cause, as you know, extrem sickness.

This behavior is very strange and I'm not 100% sure if it's the sdk or unity or something completly strange... 

I tried to delete the cardboard settings to come back to default viewer (deleted the app cache / data) and it worked once: I got my framerate back ;) - again, after switching viewer (this time in the cardboard app while my app was closed) it starts with 50fps and goes down to 25fps after 3 seconds.

It's also not good, that I can't reset the viewer in the cardboard app itself to a standard setting. The app / cache delete thing doesn't work everytime... at the moment I just don't know what viewer is used, because cardboard app says zaak, but I delete the data and cache.

Do you have similar problems or an idea what causes this?

**Comment by smdol** [comment]
If I read you right, you get 50-60 fps in the default (old) Cardboard, but 25 fps in the Cardboard v2?  Is your scene very complex / active?  The new viewer has a wider FOV, so it will have to render more stuff (twice -- once per eye).  Less stuff gets culled out by the frustum which could lower your frame rate, although a 50% drop still seems excessive.

**Comment by noemis84** [comment]
It seems, that this is not a common problem. I thought, maybe there are other people with similiar problems.

No, my scene is not complex...and even with a wider fov you wouldn't see more objects. This problem appears until now only on a samsung s6 (tested two devices). On my moto x 2nd I have constant 60fps. I still rework the scene and do some code review, maybe I find a bug. If so, I'll post it here... thank you for giving an advice.

**Comment by noemis84** [comment]
After some further tests I made the problem seem to be more clearly: it wasn't switching the viewer, this just happend the same time we used the app longer.

After my last post I created a very simple unity project: a sphere with 4k texture (spherical 360), the cradboardMain prefab, an audio loop and a fps counter... the same problem appeared, after a couple of time the framerate droped down from 60 to around 30. Only on S6. So I could be sure, it has nothing to do with my other unity project.

After a short web search I found this (the long answer is important and describes the problem I think very well): https://www.reddit.com/r/GoogleCardboard/comments/3e4iva/galaxy_s6_cardboard_performance/

If I had a very complex scene I wouldn't complain about the s6 throtteling down, but as described above, the scene is very simple. So maybe we could find a solution inside the SDK to use the resources of the phone better... I doubt that the s6 is the only phone with this problem.

Another note: the s6 is slower after around 5min... but the backside is just warm, not hot. In many other usecases the s6 becomes much warmer.

**Comment by smdol** [comment]
This may be worth trying with the new v0.5.2 release.  You can try the new in-Unity distortion method.  Also, you can downscale the RenderTexture size using the slider on the Cardboard component.  Another switch you might try is to use the VertexLit rendering path.

**Comment by noemis84** [comment]
You're right. After upgrading to 0.5.2. we have a constant high framerate (still with native distortion, unitys was very slow in a first try, I'll investigate that when I've more time)... after 10min the s6 was hotter, but no framerate drop down. I close this issue for now.
