### ISSUE TITLE
Sensor Fusion app integration - possible/beneficial ?

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#86]
Someone on reddit recommended trying Sensor Fusion app https://play.google.com/store/apps/details?id=org.hitlabnz.sensor_fusion_demo when we were talking about latency and all that good stuff.

So I tried it and it seems to be super responsive. Too bad there is no VR mode to try it, but maybe it would make sense to integrate into SDK / Unity SDK. Is it possible ? Would Cardboard VR benefit from such integration?

**Comment by kevinlido** [comment]
can anyone answer this? I have the same question

**Comment by smdol** [comment]
The new v0.5.2 release has a different sensor fusion algorithm from before.  It should work on a wider variety of phones.  

I actually saw this app (and the author's thesis) last year and showed it to coworkers.  It could be integrated into the SDK if someone wrote their own derivation of BaseVRDevice.cs to use it (perhaps as a native code plugin).  I don't know enough to say if it would work better than the current algorithm.
