### ISSUE TITLE
Drift issues. No Sensor Fusion present in the SDK.

### ISSUE THREAD

**Issue by jitsuCM** [googlesamples/cardboard-unity#9]
Hi,

   First of all i *AM* aware of the fact that it was stated explicitly that there is no drift compensation present in the SDK.

However, I still find it unreasonable that the SDK lacks it. A Sensor Fusion implementation would be a way to go. Currently there is no way to handle the drift (which is sometimes very serious, i've seen as much as ~+20 deg on y axis per second on some devices), except for to compensate the rotation value after grabbing it from Cardboard.SDK.* which is a bit too late. The drift should be handled internally.

For example this is an iOS library with sensor fusion perfectly in place: https://github.com/orbotix/Sphero-AR-SDK/tree/master/Unity%20Sample

Also, Occulus insight on this: https://www.oculus.com/blog/sensor-fusion-keeping-it-simple/
Unity occulus SDK also has it.

I just find it too awkard that Google authored SDK is lacking such basic functionality, especially when this is potentially one of the bleeding edge technologies.

**Comment by zfarm** [comment]
I heard that That this is in place, or some kind of calibration is on board now? Is that true?

**Comment by frankcarey** [comment]
Just a note, but removing the magnet from my cardboard has eliminated the yaw drift issues I'd had previously with the same sdk.

**Comment by smdol** [comment]
New release 0.4.9 has drift correction enabled by default.

**Comment by andregm3** [comment]
This Demo app with free open-source code shows how some sensor fusion modes results in no more DRIFT ! I wonder if someone know how to add this to Cardboard sdk:

https://play.google.com/store/apps/details?id=org.hitlabnz.sensor_fusion_demo
