### ISSUE TITLE
Loading new scene still keeping cardboard stuff visible

### ISSUE THREAD

**Issue by sebrk** [googlesamples/cardboard-unity#91]
The 0.5.1 release of the plugin has a release note stating the following to be fixed.

- VR Mode was being left enabled when loading a scene that had no Cardboard script, which affected rendering and input handling in the new scene. All VR Mode state is reset on scene load now.

Unfortunately this is not true. While it works better than before, loading a VR scene -> loading a non-VR scene -> loading a VR scene and so forth ultimately ends up with a distorted mix of both scenes. Note that the Cardboard settings button is still enabled and usable but not any buttons from the non-VR scene. The below screenshot is showing: after loading a non-VR scene coming from a cardboard VR-scene.

- Using Unity3D plugin: 0.5.1 (and removed everything prior to update)
- Unity3D PRO 4.6.8f1
- Tested on both iOS and Android

Note: Screen is rotated to left landscape before loading VR-scene and rotated to portrait in Start() of the non-VR scene.

![screen](https://cloud.githubusercontent.com/assets/748611/10244370/f9da85d4-68fe-11e5-9f67-1e1895fee151.png)

**Comment by smdol** [comment]
Two questions:
1)  Does this still happen with v0.5.2?
2)  If you add a Cardboard script to the non-VR scene, and set its *VRModeEnabled* property to **false** in the editor, does that stop the issue?

**Comment by Smorpheus** [comment]
Confirmed this is still happening in 0.5.2. When using the technique described in #2, Android Device is still drawing one frame of UI Overlay. This does not occur in editor.

**Comment by smdol** [comment]
OK, this is turning out to be harder to squash than expected.  Here's another workaround:  In your code that is about to launch a non-VR scene, turn off the UI layer like this:

    Cardboard.SDK.EnableSettingsButton = false;
    Cardboard.SDK.EnableAlignmentMarker = false;
    Cardboard.SDK.BackButtonMode = Cardboard.SDK.BackButtonModes.Off;

(Use that last line only if you don't want the Back Button in the non-VR scene.)

**Comment by smdol** [comment]
This bug should be fixed in the new v0.6 release of the SDK.
