### ISSUE TITLE
ShowSettingsDialog() instantiates an object and destroys menu

### ISSUE THREAD

**Issue by noemis84** [googlesamples/cardboard-unity#92]
hi there,

in our cardboard app we start in portrait mode... we want to give the user some introduction to VR and also some hints for best experience. so we also want to start the settings dialog to adjust the viewer device via our options menu, and not in VR mode (we instantiate the cardboard prefab later):

but when I launch Cardboard.SDK.ShowSettingsDialog ()... the configuration dialog is shown, but after resume to the app, there is added a cardboard object/component and also the settings button and alignment marker in the scene, which is annoying... is it possible that this function really just does what it says: ShowSettingsDialog?

thank you
Simeon

**Comment by smdol** [comment]
I recommend the following steps:
1)  Add a Cardboard object to your scene.  Just put it on some gameobject.
2)  In the inspector for the Cardboard component, set VRModeEnabled = off.
3)  When you add the prefab later, use the one that does *not* have a Cardboard on it (CardboardHead), or edit your prefab and remove it.  (You don't want two Cardboard scripts in the same scene.)

So this way the Cardboard will initialize with VRMode set to off, which removes the settings button and alignment marker.  Later, after you add your prefab, you can flip Cardboard.SDK.VRModeEnabled to true to switch into VR Mode.

**Comment by noemis84** [comment]
Thank you for your fast response...this helped a lot and solved my problem. But one important not: i could NOT enter vr mode via Cardboard.SDK.enabled = true;

That worked: [some gameobject].GetComponent<Cardboard> ().VRModeEnabled = true;

Another related question: in vr mode the settings button is not visible on android, but if you tap on the screen on the position where it was (on android), the settings dialog appears. is this wanted?

**Comment by noemis84** [comment]
Another related Question: can I define which device is assumed/standard? Like:
GetComponent<Cardboard>().deviceType = CardboardProfile.DeviceTypes.CardboardMay2015;

I get errors while building... it would be nice, if there's a way to define the device via script on runtime... I ask, because a customers bought over 2000 cardboards V2 and I want the app be preconfigured...

**Comment by smdol** [comment]
Yes, there's a property on Cardboard called DefaultDeviceProfile.  You set it to the URI that you would get from using the online profile generator.  This property is not shown in the inspector; you have to edit the script.  

For Cardboard V2 , the proper initialization is:

    new Uri("http://google.com/cardboard/cfg?p=CgZHb29nbGUSEkNhcmRib2FyZCBJL08gMjAxNR0J-SA9JQHegj0qEAAAcEIAAHBCAABwQgAAcEJYADUpXA89OghX8as-YrENP1AAYAM")

It will only take affect for users who have not scanned a QR code, because the user's choice takes priority.

**Comment by smdol** [comment]
Also, your line above:

    Cardboard.SDK.enabled = true;

is not how you enable VR mode.  The proper code is:

    Cardboard.SDK.VRModeEnabled = true;

If the settings button is not appearing, that is a bug.

**Comment by noemis84** [comment]
Thank you!. I'll try that.

Cardboard.SDK.ShowSettingsDialog () works well on android... Device detected :)

On IOS it doesn't look good (canNotFindSymbol / SkipButtonLabel?) and I get an error on bottom of the screen: parsing failed.

**Comment by noemis84** [comment]
And another problem: now after adding the cardboard component (to enable the settings thing, which works on android, but not on ios) on iphone after app start the "Let's setup you device" dialog appears again (which wasn't a problem if the cardboard prefab was instantiated later), which is definitly not what we wanted: after starting an app seeing something completly different.

Any ideas? Do you know, why the labels on ios are missing?

**Comment by smdol** [comment]
See the instructions here:
https://developers.google.com/cardboard/unity/get-started-ios
for steps you have to do to the Xcode project that Unity generates.  This will fix the missing labels.

This dialog will normally appear the first time a Cardboard object is instantiated in the scene.  But if you use the default URI, this should be skipped.  And if you really want to make certain that the setup dialog does not appear, edit CardboardiOSDevice.cs OnFocus() method.
