### ISSUE TITLE
[Feat. request] Gamepad input C# script for player movement

### ISSUE THREAD

**Issue by motorsep** [googlesamples/cardboard-unity#97]
Could you guys please add bluetooth gamepad input handling script to player controller (left thumb stick would move player with constant speed forward/back and strafe left/right; with speed multiplier) ?

I tried messing with it but there are no training materials on the subject online :(

I am using http://www.amazon.com/BEBONCOOL-Wireless-Bluetooth-Controller-Gamepad/dp/B00UJC2KW0/ref=sr_1_4?ie=UTF8&qid=1443372009 and I got it working with Gear VR on desktop (Editor) and on mobile. Although Oculus provides gamepad input script. All I had to do was figuring out the axes and variable(?) to teak in the Unity's input manager.

Thanks beforehand.

**Comment by smdol** [comment]
It's a bit out of scope for the Cardboard SDK right now, so I don't have any idea when this would happen.  I found a nice rundown here:
https://forums.oculus.com/viewtopic.php?t=18509#p234874
That talks about how to get your Bluetooth controller working with Unity and Android, using the Oculus code as a starting point.  If you want to get going on this soon, this is the way to go.

**Comment by grobm** [comment]
Also consider just looking at bluetooth implementations in Unity for gamepads.

**Comment by nathanmartz** [comment]
Closing as out of scope for Cardboard SDK.
