### ISSUE TITLE
Occasionally loses mesh rendering in iPhone 5

### ISSUE THREAD

**Issue by doctormobius** [googlesamples/cardboard-unity#98]
I'd first like to say I love the product, thanks for all the effort that has clearly gone into it!

I'm finding that my Unity 5.2.1f1 game will turn all meshes invisible whilst an explosion particle effect occurs on iPhone 5 but not iPhone 6 (whether I use Cardboard SDK v0.50 or v0.52). If I'm playing in stereo mode when it happens, the screen stretches strangely too.

It's making me think it's possibly related to GLES 2.0 as I'm using the "auto graphics API" option at the moment, and that would cause the game to run using Metal in iPhone 6, but GLES 2.0 on the iPhone 5.

Screenshot: Lining up crosshair for a shot... meshes visible
![working](https://cloud.githubusercontent.com/assets/15131748/10593236/bbca7452-76b9-11e5-840c-42feae27f1e0.PNG)

Screenshot: Explosion particle effect visible near crosshair hides meshes
![glitch](https://cloud.githubusercontent.com/assets/15131748/10593237/bbcb0eda-76b9-11e5-868f-aa62803f64e5.PNG)

Some of the other posts suggest turning off Direct Rendering as a possible fix, but in the v0.52 SDK that option doesn't seem to be there. I've checked and I'm using the "Unity" method for the distortion, if that helps. I'd really like to stay on v0.52 as the new gyro drift correction has solved the problem for all my Galaxy S6 customers and it runs a lot smoother than the earlier version...

Any ideas smdol, you're my only hope?!

**Comment by smdol** [comment]
Direct Render is on the StereoController.  Definitely give it a shot.  Let me know if it has any effect or not, and we'll go from there.

**Comment by doctormobius** [comment]
Thanks for the swift reply - I recompiled with the Direct Render option disabled and ran the game on an iPhone 5, but the glitch still occurs.

It's 1am here so I'm going to have to call it a night, but as I'm using an old 2009 MacBook which takes ages to do anything, which of these areas do you think I should focus on in the morning?

Try using "Native" distortion method instead of "Unity"?
Try with a solid colour rather than the skybox?
Try turning off occlusion culling on the mono/stereo cameras?
Try turning off the dynamic light in the explosion effect?

**Comment by smdol** [comment]
Quick question:  Are you adding an image effect at runtime?  The way the screen is drawing in the 2nd screenshot is usually caused by image effects (or deferred lighting sometimes).  Direct Render is supposed to fix this, but it works by adding a final image effect to the cameras -- it has to be last in the chain.

**Comment by doctormobius** [comment]
I'm not adding any image effects, and I'm definitely using forward rendering. I'm going to try and recreate this on my iPhone 6 by forcing GLES 2.0 instead of letting it use Metal.

**Comment by doctormobius** [comment]
Couldn't get it to glitch using GLES 2.0 on my iPhone 6, but after trying a few things I discovered the culprit was a dynamic light in the explosion effect which causes the glitch when close enough to the camera.

Looks like it's a general Unity issue rather than related to anything related to the Cardboard SDK.

Case closed!
