### ISSUE TITLE
iPhone 6 + 0.5.2 SDK: extreme steady drift

### ISSUE THREAD

**Issue by smxthereisonlyone** [googlesamples/cardboard-unity#99]
Hey guys,

the new sdk has severe drift issues. It is steadily drifting.

What to do?

**Comment by mschneider** [comment]
It happens to with auto drift correction enabled and disabled on iOS 8 & 9. iPhone 6 & 6+

You can verify it by displaying a sphere with a grid and holding the phone still in your hand. The sphere should slowly but constantly rotate with a yaw of 1deg in portrait

**Comment by smdol** [comment]
I'll let our sensor people know.  If you set the phone down for about 10 seconds while the app is running, does it stabilize?  (Try it with the phone in the viewer, facing forward -- i.e. don't put the back of the phone on the table.)

**Comment by PatrionDigital** [comment]
I've seen this issue too.

On an iPhone 6S with iOS 9.0.2 the camera rig pan slowly drifts to the right. This is even after setting the phone on a table.

**Comment by smdol** [comment]
Our QA gruop in house is unable to repro with the phones in house, but it could be that it shows up worse on some phones (i.e. specific units) than on others.  The new sensor fusion algorithm uses the raw gyro readings, and works the same on Android and on iOS.  I'm not a sensor expert, so I don't know a whole lot more than that, but I will keep feeding back your updates to the team.

**Comment by AndreGroeschel** [comment]
just looked into CardboardiOSDevice.cs and on line 79 auto drift correction gets turned off. Is there any specific reason for not using it on iOS?

**Comment by justinwasilenko** [comment]
I have a beta tester using a HTC One m7 and he is also reporting the extreme drift in the newest build of my game using the newest Cardboard plugin. Restarting the phone helped, but as time went on the drift got worse.

**Comment by smdol** [comment]
@justinwasilenko Can you ask your tester if the phone is getting really warm?  I know that makes the gyro drift change, so we should at least collect that data point.  (One of my coworkers took this temperature testing to an extreme: he refrigerated his phone for 20 minutes and then tested drift.  I'm *not* asking for anyone to do that!)

**Comment by smxthereisonlyone** [comment]
@smdol thanks for going to such extremes. I really appreciate that you want to get it right. But, will you accelerate your update schedule of the SDK? The 0.5.1 was released 2 months ago, if I'm not mistaken. This is ages in the VR world - we need quicker support.

**Comment by D3m0n92** [comment]
@smxthereisonlyone  Yep...

**Comment by justinwasilenko** [comment]
@smdol Not not any warmer than normal or when playing the game.

**Comment by smdol** [comment]
Facepalm.  OK, it looks like I accidentally left in the line of code to disable the gyro drift correction for iOS from the old library, which didn't use our drift correction on iOS (it was tuned for Android only then):

    public override void Init() {
        isOpenGL = isOpenGLAPI();
        setSyncWithCardboardEnabled(Cardboard.SDK.SyncWithCardboardApp);
        base.Init();
        // For iOS don't use Drift Correction.
        SetAutoDriftCorrectionEnabled(false);   //  <--  OOPS, should have been deleted
    }

Can you try again, after removing this line?

**Comment by AndreGroeschel** [comment]
removed the line and tried it but but the drift on iOS is much worse than in 0.5.1 :( When holding the device in portrait mode there is a slow but constant rotation. So for now we switched back to 0.5.1

**Comment by smdol** [comment]
OK.  I just got the same feedback from another tester as well, so it's probably not recommended.  Thanks for trying it.

**Comment by brianchasalow** [comment]
FWIW, I disable gyro functionality _completely_ in the google cardboard API, and wrote a script that uses Unity's built-in gyro instead. Works way better... hope Google fixes this soon.

**Comment by pzmudzinski** [comment]
@brianchasalow could you share your solution?

**Comment by dill0wn** [comment]
I'm seeing the same issues, but on a Galaxy S5.  There seems to be an extremely subtle drift when looking straight ahead.  But after looking back and forth left and right for several minutes, I'm eventually looking practically behind where I start.  We have auto-drift correction enabled.

Is this just where the state of the technology is right now, and there's no way to fix it?  Or might we be doing something wrong?

**Comment by smxthereisonlyone** [comment]
So, any update on when 0.5.3 is coming out?

**Comment by smdol** [comment]
The new v0.6 release is out, and iPhone drift should be much improved.
